// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_rows.sql

package store

import (
	"context"
	"database/sql"
)

const latestBillingRowTime = `-- name: LatestBillingRowTime :one
SELECT COALESCE(SUM(pioneer_created_at * 0) + MAX(pioneer_created_at), 0)
FROM pool_key_billing_rows
WHERE pool_key_id = ?
`

// Most recent pioneer_created_at for a key.
// COALESCE(SUM(pioneer_created_at*0) + MAX(...)) is a workaround for
// sqlc's sqlite parser rejecting bare COALESCE(MAX(...), 0).
func (q *Queries) LatestBillingRowTime(ctx context.Context, poolKeyID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, latestBillingRowTime, poolKeyID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listBillingRowsForKeyAfter = `-- name: ListBillingRowsForKeyAfter :many
SELECT id, pool_key_id, pioneer_created_at, credit_micros, cost_micros, token_usage, model, endpoint, attributed_user_id, attribution, is_duplicate, matched_request_id, ingested_at FROM pool_key_billing_rows
WHERE pool_key_id = ?
  AND pioneer_created_at > ?
ORDER BY pioneer_created_at ASC
`

type ListBillingRowsForKeyAfterParams struct {
	PoolKeyID        string `json:"pool_key_id"`
	PioneerCreatedAt int64  `json:"pioneer_created_at"`
}

// All billing rows for a key after a given timestamp.
func (q *Queries) ListBillingRowsForKeyAfter(ctx context.Context, arg ListBillingRowsForKeyAfterParams) ([]PoolKeyBillingRow, error) {
	rows, err := q.db.QueryContext(ctx, listBillingRowsForKeyAfter, arg.PoolKeyID, arg.PioneerCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolKeyBillingRow{}
	for rows.Next() {
		var i PoolKeyBillingRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolKeyID,
			&i.PioneerCreatedAt,
			&i.CreditMicros,
			&i.CostMicros,
			&i.TokenUsage,
			&i.Model,
			&i.Endpoint,
			&i.AttributedUserID,
			&i.Attribution,
			&i.IsDuplicate,
			&i.MatchedRequestID,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingRowsForUserToday = `-- name: ListBillingRowsForUserToday :many
SELECT id, pool_key_id, pioneer_created_at, credit_micros, cost_micros, token_usage, model, endpoint, attributed_user_id, attribution, is_duplicate, matched_request_id, ingested_at FROM pool_key_billing_rows
WHERE attributed_user_id = ?
  AND pioneer_created_at >= ?
  AND pioneer_created_at < ?
ORDER BY pioneer_created_at ASC
`

type ListBillingRowsForUserTodayParams struct {
	AttributedUserID   sql.NullString `json:"attributed_user_id"`
	PioneerCreatedAt   int64          `json:"pioneer_created_at"`
	PioneerCreatedAt_2 int64          `json:"pioneer_created_at_2"`
}

// Billing rows attributed to a user in a time window.
// Caller filters duplicates and sums in Go.
func (q *Queries) ListBillingRowsForUserToday(ctx context.Context, arg ListBillingRowsForUserTodayParams) ([]PoolKeyBillingRow, error) {
	rows, err := q.db.QueryContext(ctx, listBillingRowsForUserToday, arg.AttributedUserID, arg.PioneerCreatedAt, arg.PioneerCreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolKeyBillingRow{}
	for rows.Next() {
		var i PoolKeyBillingRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolKeyID,
			&i.PioneerCreatedAt,
			&i.CreditMicros,
			&i.CostMicros,
			&i.TokenUsage,
			&i.Model,
			&i.Endpoint,
			&i.AttributedUserID,
			&i.Attribution,
			&i.IsDuplicate,
			&i.MatchedRequestID,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBillingRow = `-- name: UpsertBillingRow :exec

INSERT INTO pool_key_billing_rows (
    id, pool_key_id, pioneer_created_at, credit_micros, cost_micros,
    token_usage, model, endpoint,
    attributed_user_id, attribution, is_duplicate, matched_request_id, ingested_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type UpsertBillingRowParams struct {
	ID               string         `json:"id"`
	PoolKeyID        string         `json:"pool_key_id"`
	PioneerCreatedAt int64          `json:"pioneer_created_at"`
	CreditMicros     int64          `json:"credit_micros"`
	CostMicros       int64          `json:"cost_micros"`
	TokenUsage       int64          `json:"token_usage"`
	Model            string         `json:"model"`
	Endpoint         string         `json:"endpoint"`
	AttributedUserID sql.NullString `json:"attributed_user_id"`
	Attribution      int64          `json:"attribution"`
	IsDuplicate      int64          `json:"is_duplicate"`
	MatchedRequestID sql.NullString `json:"matched_request_id"`
	IngestedAt       int64          `json:"ingested_at"`
}

// pool_key_billing_rows: ingested pioneer billing log entries.
//
// attribution integer enum:
//
//	0 = matched        (joined to a potluck_requests row)
//	1 = judge_paired   (/llmaj/judge paired to preceding opus call)
//	2 = owner_fallback (no match, charged to key owner)
//	3 = duplicate      (double-logged by pioneer, not charged)
func (q *Queries) UpsertBillingRow(ctx context.Context, arg UpsertBillingRowParams) error {
	_, err := q.db.ExecContext(ctx, upsertBillingRow,
		arg.ID,
		arg.PoolKeyID,
		arg.PioneerCreatedAt,
		arg.CreditMicros,
		arg.CostMicros,
		arg.TokenUsage,
		arg.Model,
		arg.Endpoint,
		arg.AttributedUserID,
		arg.Attribution,
		arg.IsDuplicate,
		arg.MatchedRequestID,
		arg.IngestedAt,
	)
	return err
}
