// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"
	"database/sql"
)

const archiveConversation = `-- name: ArchiveConversation :exec
UPDATE conversations SET archived_at = ? WHERE id = ? AND user_id = ?
`

type ArchiveConversationParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
}

func (q *Queries) ArchiveConversation(ctx context.Context, arg ArchiveConversationParams) error {
	_, err := q.db.ExecContext(ctx, archiveConversation, arg.ArchivedAt, arg.ID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, user_id, title, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, title, created_at, updated_at, archived_at
`

type CreateConversationParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Title     string `json:"title"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, created_at, updated_at, archived_at FROM conversations WHERE id = ? AND user_id = ?
`

type GetConversationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT id, user_id, title, created_at, updated_at, archived_at FROM conversations
WHERE user_id = ? AND archived_at IS NULL
ORDER BY updated_at DESC
LIMIT ?
`

type ListConversationsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = ? WHERE id = ?
`

type TouchConversationParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchConversation, arg.UpdatedAt, arg.ID)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations SET title = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateConversationTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationTitle,
		arg.Title,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
