// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_spend.sql

package store

import (
	"context"
)

const getLatestRecompute = `-- name: GetLatestRecompute :one
SELECT set_at, set_by_user_id FROM user_daily_allowances
WHERE day = ?
ORDER BY set_at DESC
LIMIT 1
`

type GetLatestRecomputeRow struct {
	SetAt       int64  `json:"set_at"`
	SetByUserID string `json:"set_by_user_id"`
}

// Most recent recompute for today, for display in the dashboard.
func (q *Queries) GetLatestRecompute(ctx context.Context, day int64) (GetLatestRecomputeRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestRecompute, day)
	var i GetLatestRecomputeRow
	err := row.Scan(&i.SetAt, &i.SetByUserID)
	return i, err
}

const getUserDailyAllowance = `-- name: GetUserDailyAllowance :one
SELECT user_id, day, shared_allowance_micros, set_at, set_by_user_id FROM user_daily_allowances WHERE user_id = ? AND day = ?
`

type GetUserDailyAllowanceParams struct {
	UserID string `json:"user_id"`
	Day    int64  `json:"day"`
}

func (q *Queries) GetUserDailyAllowance(ctx context.Context, arg GetUserDailyAllowanceParams) (UserDailyAllowance, error) {
	row := q.db.QueryRowContext(ctx, getUserDailyAllowance, arg.UserID, arg.Day)
	var i UserDailyAllowance
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.SharedAllowanceMicros,
		&i.SetAt,
		&i.SetByUserID,
	)
	return i, err
}

const getUserDailySpend = `-- name: GetUserDailySpend :one
SELECT user_id, day, shared_spent_micros, private_spent_micros FROM user_daily_spend WHERE user_id = ? AND day = ?
`

type GetUserDailySpendParams struct {
	UserID string `json:"user_id"`
	Day    int64  `json:"day"`
}

func (q *Queries) GetUserDailySpend(ctx context.Context, arg GetUserDailySpendParams) (UserDailySpend, error) {
	row := q.db.QueryRowContext(ctx, getUserDailySpend, arg.UserID, arg.Day)
	var i UserDailySpend
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.SharedSpentMicros,
		&i.PrivateSpentMicros,
	)
	return i, err
}

const listUserDailyAllowancesForDay = `-- name: ListUserDailyAllowancesForDay :many
SELECT user_id, day, shared_allowance_micros, set_at, set_by_user_id FROM user_daily_allowances WHERE day = ?
`

func (q *Queries) ListUserDailyAllowancesForDay(ctx context.Context, day int64) ([]UserDailyAllowance, error) {
	rows, err := q.db.QueryContext(ctx, listUserDailyAllowancesForDay, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDailyAllowance{}
	for rows.Next() {
		var i UserDailyAllowance
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.SharedAllowanceMicros,
			&i.SetAt,
			&i.SetByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDailySpendForDay = `-- name: ListUserDailySpendForDay :many
SELECT user_id, day, shared_spent_micros, private_spent_micros FROM user_daily_spend WHERE day = ?
`

func (q *Queries) ListUserDailySpendForDay(ctx context.Context, day int64) ([]UserDailySpend, error) {
	rows, err := q.db.QueryContext(ctx, listUserDailySpendForDay, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDailySpend{}
	for rows.Next() {
		var i UserDailySpend
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.SharedSpentMicros,
			&i.PrivateSpentMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserDailyAllowance = `-- name: UpsertUserDailyAllowance :exec
INSERT INTO user_daily_allowances (
    user_id, day, shared_allowance_micros, set_at, set_by_user_id
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, day) DO UPDATE SET
    shared_allowance_micros = MAX(
        excluded.shared_allowance_micros,
        user_daily_allowances.shared_allowance_micros
    ),
    set_at         = excluded.set_at,
    set_by_user_id = excluded.set_by_user_id
`

type UpsertUserDailyAllowanceParams struct {
	UserID                string `json:"user_id"`
	Day                   int64  `json:"day"`
	SharedAllowanceMicros int64  `json:"shared_allowance_micros"`
	SetAt                 int64  `json:"set_at"`
	SetByUserID           string `json:"set_by_user_id"`
}

func (q *Queries) UpsertUserDailyAllowance(ctx context.Context, arg UpsertUserDailyAllowanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserDailyAllowance,
		arg.UserID,
		arg.Day,
		arg.SharedAllowanceMicros,
		arg.SetAt,
		arg.SetByUserID,
	)
	return err
}

const upsertUserDailySpend = `-- name: UpsertUserDailySpend :exec

INSERT INTO user_daily_spend (user_id, day, shared_spent_micros, private_spent_micros)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, day) DO UPDATE SET
    shared_spent_micros  = shared_spent_micros  + excluded.shared_spent_micros,
    private_spent_micros = private_spent_micros + excluded.private_spent_micros
`

type UpsertUserDailySpendParams struct {
	UserID             string `json:"user_id"`
	Day                int64  `json:"day"`
	SharedSpentMicros  int64  `json:"shared_spent_micros"`
	PrivateSpentMicros int64  `json:"private_spent_micros"`
}

// user_daily_spend and user_daily_allowances.
func (q *Queries) UpsertUserDailySpend(ctx context.Context, arg UpsertUserDailySpendParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserDailySpend,
		arg.UserID,
		arg.Day,
		arg.SharedSpentMicros,
		arg.PrivateSpentMicros,
	)
	return err
}
