// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"database/sql"
)

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :exec
DELETE FROM idempotency_keys WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredIdempotency, expiresAt)
	return err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT "key", user_id, api_key_id, request_hash, status, response_body, response_type, created_at, expires_at FROM idempotency_keys
WHERE key = ? AND user_id = ? AND expires_at > ?
`

type GetIdempotencyParams struct {
	Key       string `json:"key"`
	UserID    string `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotency, arg.Key, arg.UserID, arg.ExpiresAt)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.ApiKeyID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseBody,
		&i.ResponseType,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const putIdempotency = `-- name: PutIdempotency :exec
INSERT INTO idempotency_keys (
    key, user_id, api_key_id, request_hash, status,
    response_body, response_type, created_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    request_hash  = excluded.request_hash,
    status        = excluded.status,
    response_body = excluded.response_body,
    response_type = excluded.response_type,
    expires_at    = excluded.expires_at
`

type PutIdempotencyParams struct {
	Key          string         `json:"key"`
	UserID       string         `json:"user_id"`
	ApiKeyID     sql.NullString `json:"api_key_id"`
	RequestHash  string         `json:"request_hash"`
	Status       int64          `json:"status"`
	ResponseBody []byte         `json:"response_body"`
	ResponseType string         `json:"response_type"`
	CreatedAt    int64          `json:"created_at"`
	ExpiresAt    int64          `json:"expires_at"`
}

func (q *Queries) PutIdempotency(ctx context.Context, arg PutIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, putIdempotency,
		arg.Key,
		arg.UserID,
		arg.ApiKeyID,
		arg.RequestHash,
		arg.Status,
		arg.ResponseBody,
		arg.ResponseType,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
