// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"
)

const createContribution = `-- name: CreateContribution :one
INSERT INTO contributions (id, user_id, amount_micros, note, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, amount_micros, note, created_at
`

type CreateContributionParams struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	AmountMicros int64  `json:"amount_micros"`
	Note         string `json:"note"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error) {
	row := q.db.QueryRowContext(ctx, createContribution,
		arg.ID,
		arg.UserID,
		arg.AmountMicros,
		arg.Note,
		arg.CreatedAt,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountMicros,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listContributionsForUser = `-- name: ListContributionsForUser :many
SELECT id, user_id, amount_micros, note, created_at FROM contributions
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListContributionsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListContributionsForUser(ctx context.Context, arg ListContributionsForUserParams) ([]Contribution, error) {
	rows, err := q.db.QueryContext(ctx, listContributionsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contribution{}
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountMicros,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimatedSpends = `-- name: ListEstimatedSpends :many
SELECT id, user_id, stream_id, model, input_tokens, output_tokens, amount_micros, is_estimated, created_at, api_key_id FROM spends WHERE is_estimated = 1 ORDER BY created_at ASC LIMIT ?
`

func (q *Queries) ListEstimatedSpends(ctx context.Context, limit int64) ([]Spend, error) {
	rows, err := q.db.QueryContext(ctx, listEstimatedSpends, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spend{}
	for rows.Next() {
		var i Spend
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StreamID,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.AmountMicros,
			&i.IsEstimated,
			&i.CreatedAt,
			&i.ApiKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAllocations = `-- name: ListUserAllocations :many
SELECT
    u.id          AS user_id,
    u.display_name,
    u.email,
    COALESCE(SUM(c.amount_micros), 0) AS contributed_micros,
    COALESCE((SELECT SUM(s.amount_micros) FROM spends s WHERE s.user_id = u.id), 0) AS spent_micros
FROM users u
LEFT JOIN contributions c ON c.user_id = u.id
GROUP BY u.id, u.display_name, u.email
ORDER BY contributed_micros DESC
`

type ListUserAllocationsRow struct {
	UserID            string      `json:"user_id"`
	DisplayName       string      `json:"display_name"`
	Email             string      `json:"email"`
	ContributedMicros interface{} `json:"contributed_micros"`
	SpentMicros       interface{} `json:"spent_micros"`
}

// Per-user contribution totals, spend totals, and derived balance.
// Used by the allocation calculator on the dashboard.
func (q *Queries) ListUserAllocations(ctx context.Context) ([]ListUserAllocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserAllocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAllocationsRow{}
	for rows.Next() {
		var i ListUserAllocationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Email,
			&i.ContributedMicros,
			&i.SpentMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumContributions = `-- name: SumContributions :one
SELECT COALESCE(SUM(amount_micros), 0) FROM contributions WHERE user_id = ?
`

func (q *Queries) SumContributions(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumContributions, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const sumSpends = `-- name: SumSpends :one
SELECT COALESCE(SUM(amount_micros), 0) FROM spends WHERE user_id = ?
`

func (q *Queries) SumSpends(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumSpends, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const upsertSpend = `-- name: UpsertSpend :one
INSERT INTO spends (
    id, user_id, stream_id, model, input_tokens, output_tokens,
    amount_micros, is_estimated, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(stream_id) DO UPDATE SET
    input_tokens  = excluded.input_tokens,
    output_tokens = excluded.output_tokens,
    amount_micros = excluded.amount_micros,
    is_estimated  = excluded.is_estimated
RETURNING id, user_id, stream_id, model, input_tokens, output_tokens, amount_micros, is_estimated, created_at, api_key_id
`

type UpsertSpendParams struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	StreamID     string `json:"stream_id"`
	Model        string `json:"model"`
	InputTokens  int64  `json:"input_tokens"`
	OutputTokens int64  `json:"output_tokens"`
	AmountMicros int64  `json:"amount_micros"`
	IsEstimated  int64  `json:"is_estimated"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) UpsertSpend(ctx context.Context, arg UpsertSpendParams) (Spend, error) {
	row := q.db.QueryRowContext(ctx, upsertSpend,
		arg.ID,
		arg.UserID,
		arg.StreamID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.AmountMicros,
		arg.IsEstimated,
		arg.CreatedAt,
	)
	var i Spend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StreamID,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.AmountMicros,
		&i.IsEstimated,
		&i.CreatedAt,
		&i.ApiKeyID,
	)
	return i, err
}
