// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
	"database/sql"
)

const appendAssistantContent = `-- name: AppendAssistantContent :exec
UPDATE messages SET content = content || ? WHERE id = ?
`

type AppendAssistantContentParams struct {
	Content string `json:"content"`
	ID      string `json:"id"`
}

func (q *Queries) AppendAssistantContent(ctx context.Context, arg AppendAssistantContentParams) error {
	_, err := q.db.ExecContext(ctx, appendAssistantContent, arg.Content, arg.ID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, client_id, role, content, model, created_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ClientID,
		&i.Role,
		&i.Content,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesForConversation = `-- name: ListMessagesForConversation :many
SELECT id, conversation_id, client_id, role, content, model, created_at FROM messages
WHERE conversation_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMessagesForConversation(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ClientID,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessage = `-- name: UpsertMessage :one
INSERT INTO messages (id, conversation_id, client_id, role, content, model, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(conversation_id, client_id) DO UPDATE SET
    content = excluded.content
RETURNING id, conversation_id, client_id, role, content, model, created_at
`

type UpsertMessageParams struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	ClientID       sql.NullString `json:"client_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Model          sql.NullString `json:"model"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, upsertMessage,
		arg.ID,
		arg.ConversationID,
		arg.ClientID,
		arg.Role,
		arg.Content,
		arg.Model,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ClientID,
		&i.Role,
		&i.Content,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
