// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type ApiKey struct {
	ID              string        `json:"id"`
	UserID          string        `json:"user_id"`
	KeyHash         string        `json:"key_hash"`
	KeyWord         string        `json:"key_word"`
	KeyLast4        string        `json:"key_last4"`
	Name            string        `json:"name"`
	MaxBudgetMicros sql.NullInt64 `json:"max_budget_micros"`
	SpentMicros     int64         `json:"spent_micros"`
	LastUsedAt      sql.NullInt64 `json:"last_used_at"`
	CreatedAt       int64         `json:"created_at"`
	RevokedAt       sql.NullInt64 `json:"revoked_at"`
}

type Contribution struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	AmountMicros int64  `json:"amount_micros"`
	Note         string `json:"note"`
	CreatedAt    int64  `json:"created_at"`
}

type Conversation struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Title      string        `json:"title"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ArchivedAt sql.NullInt64 `json:"archived_at"`
}

type IdempotencyKey struct {
	Key          string         `json:"key"`
	UserID       string         `json:"user_id"`
	ApiKeyID     sql.NullString `json:"api_key_id"`
	RequestHash  string         `json:"request_hash"`
	Status       int64          `json:"status"`
	ResponseBody []byte         `json:"response_body"`
	ResponseType string         `json:"response_type"`
	CreatedAt    int64          `json:"created_at"`
	ExpiresAt    int64          `json:"expires_at"`
}

type Message struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	ClientID       sql.NullString `json:"client_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Model          sql.NullString `json:"model"`
	CreatedAt      int64          `json:"created_at"`
}

type ModelPrice struct {
	Model             string `json:"model"`
	InputMicrosPer1k  int64  `json:"input_micros_per_1k"`
	OutputMicrosPer1k int64  `json:"output_micros_per_1k"`
	UpdatedAt         int64  `json:"updated_at"`
}

type ModelsCatalog struct {
	ID                          string         `json:"id"`
	Label                       string         `json:"label"`
	Description                 string         `json:"description"`
	ContextWindow               sql.NullInt64  `json:"context_window"`
	MaxOutputTokens             sql.NullInt64  `json:"max_output_tokens"`
	IsChat                      int64          `json:"is_chat"`
	Tier                        sql.NullString `json:"tier"`
	InputPricePerMillionMicros  sql.NullInt64  `json:"input_price_per_million_micros"`
	OutputPricePerMillionMicros sql.NullInt64  `json:"output_price_per_million_micros"`
	RawJson                     string         `json:"raw_json"`
	RefreshedAt                 int64          `json:"refreshed_at"`
}

type PoolKey struct {
	ID                       string         `json:"id"`
	UserID                   string         `json:"user_id"`
	Label                    string         `json:"label"`
	KeyCiphertext            string         `json:"key_ciphertext"`
	KeyFingerprint           string         `json:"key_fingerprint"`
	Active                   int64          `json:"active"`
	DailyLimitMicros         int64          `json:"daily_limit_micros"`
	TodayDate                int64          `json:"today_date"`
	TodayMicros              int64          `json:"today_micros"`
	TotalMicros              int64          `json:"total_micros"`
	RequestCount             int64          `json:"request_count"`
	CreatedAt                int64          `json:"created_at"`
	LastUsedAt               sql.NullInt64  `json:"last_used_at"`
	MaxMicros                int64          `json:"max_micros"`
	SharedMicros             int64          `json:"shared_micros"`
	PioneerTeamID            sql.NullString `json:"pioneer_team_id"`
	PioneerPaymentPlan       sql.NullString `json:"pioneer_payment_plan"`
	PioneerCreditLimitMicros sql.NullInt64  `json:"pioneer_credit_limit_micros"`
	PioneerRemainingMicros   sql.NullInt64  `json:"pioneer_remaining_micros"`
	PioneerHealth            int64          `json:"pioneer_health"`
	PioneerUnhealthySince    sql.NullInt64  `json:"pioneer_unhealthy_since"`
	PendingValidation        int64          `json:"pending_validation"`
	LastBillingSyncAt        sql.NullInt64  `json:"last_billing_sync_at"`
	RevokedAt                sql.NullInt64  `json:"revoked_at"`
}

type PoolKeyBillingRow struct {
	ID               string         `json:"id"`
	PoolKeyID        string         `json:"pool_key_id"`
	PioneerCreatedAt int64          `json:"pioneer_created_at"`
	CreditMicros     int64          `json:"credit_micros"`
	CostMicros       int64          `json:"cost_micros"`
	TokenUsage       int64          `json:"token_usage"`
	Model            string         `json:"model"`
	Endpoint         string         `json:"endpoint"`
	AttributedUserID sql.NullString `json:"attributed_user_id"`
	Attribution      int64          `json:"attribution"`
	IsDuplicate      int64          `json:"is_duplicate"`
	MatchedRequestID sql.NullString `json:"matched_request_id"`
	IngestedAt       int64          `json:"ingested_at"`
}

type PotluckRequest struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	ApiKeyID         sql.NullString `json:"api_key_id"`
	PoolKeyID        sql.NullString `json:"pool_key_id"`
	Surface          string         `json:"surface"`
	Model            string         `json:"model"`
	StartedAt        int64          `json:"started_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	PromptTokens     sql.NullInt64  `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64  `json:"completion_tokens"`
	TotalTokens      sql.NullInt64  `json:"total_tokens"`
	Status           string         `json:"status"`
	ErrorCode        sql.NullString `json:"error_code"`
}

type Session struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	CreatedAt  int64          `json:"created_at"`
	ExpiresAt  int64          `json:"expires_at"`
	LastUsedAt int64          `json:"last_used_at"`
	Ip         sql.NullString `json:"ip"`
	UserAgent  sql.NullString `json:"user_agent"`
}

type Spend struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	StreamID     string         `json:"stream_id"`
	Model        string         `json:"model"`
	InputTokens  int64          `json:"input_tokens"`
	OutputTokens int64          `json:"output_tokens"`
	AmountMicros int64          `json:"amount_micros"`
	IsEstimated  int64          `json:"is_estimated"`
	CreatedAt    int64          `json:"created_at"`
	ApiKeyID     sql.NullString `json:"api_key_id"`
}

type Stream struct {
	ID                 string         `json:"id"`
	ConversationID     string         `json:"conversation_id"`
	UserID             string         `json:"user_id"`
	AssistantMessageID sql.NullString `json:"assistant_message_id"`
	IdempotencyKey     string         `json:"idempotency_key"`
	Model              string         `json:"model"`
	Status             string         `json:"status"`
	ErrorCode          sql.NullString `json:"error_code"`
	ErrorMessage       sql.NullString `json:"error_message"`
	StartedAt          int64          `json:"started_at"`
	FinishedAt         sql.NullInt64  `json:"finished_at"`
}

type StreamChunk struct {
	StreamID  string `json:"stream_id"`
	Seq       int64  `json:"seq"`
	Event     string `json:"event"`
	Data      string `json:"data"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID                 string         `json:"id"`
	Email              string         `json:"email"`
	DisplayName        string         `json:"display_name"`
	CreatedAt          int64          `json:"created_at"`
	LastSeenAt         sql.NullInt64  `json:"last_seen_at"`
	HcaID              sql.NullString `json:"hca_id"`
	SlackID            sql.NullString `json:"slack_id"`
	VerificationStatus sql.NullString `json:"verification_status"`
	CustomDisplayName  int64          `json:"custom_display_name"`
}

type UserDailyAllowance struct {
	UserID                string `json:"user_id"`
	Day                   int64  `json:"day"`
	SharedAllowanceMicros int64  `json:"shared_allowance_micros"`
	SetAt                 int64  `json:"set_at"`
	SetByUserID           string `json:"set_by_user_id"`
	FloorMicros           int64  `json:"floor_micros"`
	BonusMicros           int64  `json:"bonus_micros"`
	PredictedTotalMicros  int64  `json:"predicted_total_micros"`
	HistoryDaysUsed       int64  `json:"history_days_used"`
}

type UserDailySpend struct {
	UserID             string `json:"user_id"`
	Day                int64  `json:"day"`
	SharedSpentMicros  int64  `json:"shared_spent_micros"`
	PrivateSpentMicros int64  `json:"private_spent_micros"`
}
