// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models_catalog.sql

package store

import (
	"context"
	"database/sql"
)

const getModelCatalogRefreshedAt = `-- name: GetModelCatalogRefreshedAt :one
SELECT COALESCE(MIN(refreshed_at), 0) FROM models_catal
`

// Oldest refreshed_at across all models — tells us when the catalog is stale.
func (q *Queries) GetModelCatalogRefreshedAt(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getModelCatalogRefreshedAt)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listModelCatalog = `-- name: ListModelCatalog :many
SELECT id, label, description, context_window, max_output_tokens, is_chat, tier, input_price_per_million_micros, output_price_per_million_micros, raw_json, refreshed_at FROM models_catalog
WHERE is_chat = 1
ORDER BY tier ASC, label ASC
`

func (q *Queries) ListModelCatalog(ctx context.Context) ([]ModelsCatalog, error) {
	rows, err := q.db.QueryContext(ctx, listModelCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelsCatalog{}
	for rows.Next() {
		var i ModelsCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Description,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.IsChat,
			&i.Tier,
			&i.InputPricePerMillionMicros,
			&i.OutputPricePerMillionMicros,
			&i.RawJson,
			&i.RefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelCatalog = `-- name: UpsertModelCatalog :exec

INSERT INTO models_catalog (
    id, label, description, context_window, max_output_tokens,
    is_chat, tier,
    input_price_per_million_micros, output_price_per_million_micros,
    raw_json, refreshed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    label                           = excluded.label,
    description                     = excluded.description,
    context_window                  = excluded.context_window,
    max_output_tokens               = excluded.max_output_tokens,
    is_chat                         = excluded.is_chat,
    tier                            = excluded.tier,
    input_price_per_million_micros  = excluded.input_price_per_million_micros,
    output_price_per_million_micros = excluded.output_price_per_million_micros,
    raw_json                        = excluded.raw_json,
    refreshed_at                    = excluded.refreshed_at
`

type UpsertModelCatalogParams struct {
	ID                          string         `json:"id"`
	Label                       string         `json:"label"`
	Description                 string         `json:"description"`
	ContextWindow               sql.NullInt64  `json:"context_window"`
	MaxOutputTokens             sql.NullInt64  `json:"max_output_tokens"`
	IsChat                      int64          `json:"is_chat"`
	Tier                        sql.NullString `json:"tier"`
	InputPricePerMillionMicros  sql.NullInt64  `json:"input_price_per_million_micros"`
	OutputPricePerMillionMicros sql.NullInt64  `json:"output_price_per_million_micros"`
	RawJson                     string         `json:"raw_json"`
	RefreshedAt                 int64          `json:"refreshed_at"`
}

// models_catalog: hourly-refreshed cache of /v1/models + /base-models.
func (q *Queries) UpsertModelCatalog(ctx context.Context, arg UpsertModelCatalogParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelCatalog,
		arg.ID,
		arg.Label,
		arg.Description,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.IsChat,
		arg.Tier,
		arg.InputPricePerMillionMicros,
		arg.OutputPricePerMillionMicros,
		arg.RawJson,
		arg.RefreshedAt,
	)
	return err
}
