// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Contribution struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	AmountMicros int64  `json:"amount_micros"`
	Note         string `json:"note"`
	CreatedAt    int64  `json:"created_at"`
}

type Conversation struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Title      string        `json:"title"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ArchivedAt sql.NullInt64 `json:"archived_at"`
}

type Message struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	ClientID       sql.NullString `json:"client_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Model          sql.NullString `json:"model"`
	CreatedAt      int64          `json:"created_at"`
}

type ModelPrice struct {
	Model             string `json:"model"`
	InputMicrosPer1k  int64  `json:"input_micros_per_1k"`
	OutputMicrosPer1k int64  `json:"output_micros_per_1k"`
	UpdatedAt         int64  `json:"updated_at"`
}

type Session struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	CreatedAt  int64  `json:"created_at"`
	ExpiresAt  int64  `json:"expires_at"`
	LastUsedAt int64  `json:"last_used_at"`
}

type Spend struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	StreamID     string `json:"stream_id"`
	Model        string `json:"model"`
	InputTokens  int64  `json:"input_tokens"`
	OutputTokens int64  `json:"output_tokens"`
	AmountMicros int64  `json:"amount_micros"`
	IsEstimated  int64  `json:"is_estimated"`
	CreatedAt    int64  `json:"created_at"`
}

type Stream struct {
	ID                 string         `json:"id"`
	ConversationID     string         `json:"conversation_id"`
	UserID             string         `json:"user_id"`
	AssistantMessageID sql.NullString `json:"assistant_message_id"`
	IdempotencyKey     string         `json:"idempotency_key"`
	Model              string         `json:"model"`
	Status             string         `json:"status"`
	ErrorCode          sql.NullString `json:"error_code"`
	ErrorMessage       sql.NullString `json:"error_message"`
	StartedAt          int64          `json:"started_at"`
	FinishedAt         sql.NullInt64  `json:"finished_at"`
}

type StreamChunk struct {
	StreamID  string `json:"stream_id"`
	Seq       int64  `json:"seq"`
	Event     string `json:"event"`
	Data      string `json:"data"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID          string        `json:"id"`
	Email       string        `json:"email"`
	DisplayName string        `json:"display_name"`
	CreatedAt   int64         `json:"created_at"`
	LastSeenAt  sql.NullInt64 `json:"last_seen_at"`
}
