// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pool_keys_v2.sql

package store

import (
	"context"
	"database/sql"
)

const activatePoolKey = `-- name: ActivatePoolKey :exec
UPDATE pool_keys SET
    active                  = 1,
    pending_validation      = 0,
    pioneer_health          = 1,
    pioneer_unhealthy_since = NULL
WHERE id = ?
`

// Called by the reconciler when a pending_validation or unauthorized key
// comes back healthy (pioneer_health=1).
func (q *Queries) ActivatePoolKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, activatePoolKey, id)
	return err
}

const listKeysNeedingHealthCheck = `-- name: ListKeysNeedingHealthCheck :many
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at FROM pool_keys
WHERE revoked_at IS NULL
ORDER BY last_billing_sync_at ASC NULLS FIRST
`

// Keys the reconciler should probe on each tick.
// Excludes permanently revoked keys.
func (q *Queries) ListKeysNeedingHealthCheck(ctx context.Context) ([]PoolKey, error) {
	rows, err := q.db.QueryContext(ctx, listKeysNeedingHealthCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolKey{}
	for rows.Next() {
		var i PoolKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyCiphertext,
			&i.KeyFingerprint,
			&i.Active,
			&i.DailyLimitMicros,
			&i.TodayDate,
			&i.TodayMicros,
			&i.TotalMicros,
			&i.RequestCount,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.MaxMicros,
			&i.SharedMicros,
			&i.PioneerTeamID,
			&i.PioneerPaymentPlan,
			&i.PioneerCreditLimitMicros,
			&i.PioneerRemainingMicros,
			&i.PioneerHealth,
			&i.PioneerUnhealthySince,
			&i.PendingValidation,
			&i.LastBillingSyncAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnhealthyKeysOlderThan = `-- name: ListUnhealthyKeysOlderThan :many
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at FROM pool_keys
WHERE pioneer_health = 2
  AND pioneer_unhealthy_since IS NOT NULL
  AND pioneer_unhealthy_since < ?
  AND revoked_at IS NULL
`

// Keys that have been unauthorized (pioneer_health=2) since before cutoff.
// Used by the reconciler to trigger permanent revocation after 14 days.
func (q *Queries) ListUnhealthyKeysOlderThan(ctx context.Context, pioneerUnhealthySince sql.NullInt64) ([]PoolKey, error) {
	rows, err := q.db.QueryContext(ctx, listUnhealthyKeysOlderThan, pioneerUnhealthySince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolKey{}
	for rows.Next() {
		var i PoolKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyCiphertext,
			&i.KeyFingerprint,
			&i.Active,
			&i.DailyLimitMicros,
			&i.TodayDate,
			&i.TodayMicros,
			&i.TotalMicros,
			&i.RequestCount,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.MaxMicros,
			&i.SharedMicros,
			&i.PioneerTeamID,
			&i.PioneerPaymentPlan,
			&i.PioneerCreditLimitMicros,
			&i.PioneerRemainingMicros,
			&i.PioneerHealth,
			&i.PioneerUnhealthySince,
			&i.PendingValidation,
			&i.LastBillingSyncAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPoolKeyRevoked = `-- name: MarkPoolKeyRevoked :exec
UPDATE pool_keys SET
    active     = 0,
    revoked_at = ?
WHERE id = ?
`

type MarkPoolKeyRevokedParams struct {
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	ID        string        `json:"id"`
}

func (q *Queries) MarkPoolKeyRevoked(ctx context.Context, arg MarkPoolKeyRevokedParams) error {
	_, err := q.db.ExecContext(ctx, markPoolKeyRevoked, arg.RevokedAt, arg.ID)
	return err
}

const pickPoolKeyForUser = `-- name: PickPoolKeyForUser :one
SELECT
    pk.id, pk.user_id, pk.label, pk.key_ciphertext, pk.key_fingerprint,
    pk.active, pk.daily_limit_micros, pk.today_date, pk.today_micros,
    pk.total_micros, pk.request_count, pk.created_at, pk.last_used_at,
    pk.max_micros, pk.shared_micros,
    pk.pioneer_team_id, pk.pioneer_payment_plan,
    pk.pioneer_credit_limit_micros, pk.pioneer_remaining_micros,
    pk.pioneer_health, pk.pioneer_unhealthy_since,
    pk.pending_validation, pk.last_billing_sync_at, pk.revoked_at,
    CASE
        WHEN pk.user_id = ? AND pk.max_micros > pk.shared_micros THEN 0
        ELSE 1
    END AS priority
FROM pool_keys pk
WHERE pk.active = 1
  AND pk.revoked_at IS NULL
  AND pk.pending_validation = 0
  AND pk.pioneer_health = 1
  AND (pk.pioneer_remaining_micros IS NULL OR pk.pioneer_remaining_micros > 10000000)
  AND pk.today_micros < pk.max_micros
ORDER BY priority ASC, pk.today_micros ASC, RANDOM()
LIMIT 1
`

type PickPoolKeyForUserRow struct {
	ID                       string         `json:"id"`
	UserID                   string         `json:"user_id"`
	Label                    string         `json:"label"`
	KeyCiphertext            string         `json:"key_ciphertext"`
	KeyFingerprint           string         `json:"key_fingerprint"`
	Active                   int64          `json:"active"`
	DailyLimitMicros         int64          `json:"daily_limit_micros"`
	TodayDate                int64          `json:"today_date"`
	TodayMicros              int64          `json:"today_micros"`
	TotalMicros              int64          `json:"total_micros"`
	RequestCount             int64          `json:"request_count"`
	CreatedAt                int64          `json:"created_at"`
	LastUsedAt               sql.NullInt64  `json:"last_used_at"`
	MaxMicros                int64          `json:"max_micros"`
	SharedMicros             int64          `json:"shared_micros"`
	PioneerTeamID            sql.NullString `json:"pioneer_team_id"`
	PioneerPaymentPlan       sql.NullString `json:"pioneer_payment_plan"`
	PioneerCreditLimitMicros sql.NullInt64  `json:"pioneer_credit_limit_micros"`
	PioneerRemainingMicros   sql.NullInt64  `json:"pioneer_remaining_micros"`
	PioneerHealth            int64          `json:"pioneer_health"`
	PioneerUnhealthySince    sql.NullInt64  `json:"pioneer_unhealthy_since"`
	PendingValidation        int64          `json:"pending_validation"`
	LastBillingSyncAt        sql.NullInt64  `json:"last_billing_sync_at"`
	RevokedAt                sql.NullInt64  `json:"revoked_at"`
	Priority                 int64          `json:"priority"`
}

// User-aware picker for private-budget routing.
// Prefers a key OWNED BY THE REQUESTING USER that still has private
// reservation room (max_micros > shared_micros AND today's spend hasn't
// filled the key yet). Falls back to the standard v2 ordering when the
// user has no eligible own-key.
//
// The CASE expression buckets eligible keys: 0 = user's own-with-private,
// 1 = anything else. Within each bucket, lowest today_micros wins.
func (q *Queries) PickPoolKeyForUser(ctx context.Context, userID string) (PickPoolKeyForUserRow, error) {
	row := q.db.QueryRowContext(ctx, pickPoolKeyForUser, userID)
	var i PickPoolKeyForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
		&i.Priority,
	)
	return i, err
}

const pickPoolKeyV2 = `-- name: PickPoolKeyV2 :one
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at FROM pool_keys
WHERE active = 1
  AND revoked_at IS NULL
  AND pending_validation = 0
  AND pioneer_health = 1
  AND (pioneer_remaining_micros IS NULL OR pioneer_remaining_micros > 10000000)
  AND today_micros < max_micros
ORDER BY today_micros ASC, RANDOM()
LIMIT 1
`

// Best active healthy key for a request:
//
//	active=1, not revoked, not pending validation
//	pioneer_health=1 (healthy)
//	pioneer_remaining_micros > 10,000,000 ($10 buffer = 1000 credits)
//	today_micros < max_micros
//
// Lowest today_micros wins; random tiebreak.
func (q *Queries) PickPoolKeyV2(ctx context.Context) (PoolKey, error) {
	row := q.db.QueryRowContext(ctx, pickPoolKeyV2)
	var i PoolKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
	)
	return i, err
}

const updatePoolKeyHealth = `-- name: UpdatePoolKeyHealth :exec

UPDATE pool_keys SET
    pioneer_health               = ?,
    pioneer_unhealthy_since      = ?,
    pioneer_team_id              = COALESCE(?, pioneer_team_id),
    pioneer_payment_plan         = COALESCE(?, pioneer_payment_plan),
    pioneer_credit_limit_micros  = COALESCE(?, pioneer_credit_limit_micros),
    pioneer_remaining_micros     = COALESCE(?, pioneer_remaining_micros),
    today_micros                 = COALESCE(?, today_micros),
    last_billing_sync_at         = ?
WHERE id = ?
`

type UpdatePoolKeyHealthParams struct {
	PioneerHealth            int64          `json:"pioneer_health"`
	PioneerUnhealthySince    sql.NullInt64  `json:"pioneer_unhealthy_since"`
	PioneerTeamID            sql.NullString `json:"pioneer_team_id"`
	PioneerPaymentPlan       sql.NullString `json:"pioneer_payment_plan"`
	PioneerCreditLimitMicros sql.NullInt64  `json:"pioneer_credit_limit_micros"`
	PioneerRemainingMicros   sql.NullInt64  `json:"pioneer_remaining_micros"`
	TodayMicros              int64          `json:"today_micros"`
	LastBillingSyncAt        sql.NullInt64  `json:"last_billing_sync_at"`
	ID                       string         `json:"id"`
}

// Pool key v2 queries: health tracking, billing sync, two-budget updates.
//
// pioneer_health integer enum:
//
//	0 = unknown
//	1 = healthy
//	2 = unauthorized
//
// Sets health and snapshots billing info from /plan-info.
// Pass NULL for optional fields to leave them unchanged.
func (q *Queries) UpdatePoolKeyHealth(ctx context.Context, arg UpdatePoolKeyHealthParams) error {
	_, err := q.db.ExecContext(ctx, updatePoolKeyHealth,
		arg.PioneerHealth,
		arg.PioneerUnhealthySince,
		arg.PioneerTeamID,
		arg.PioneerPaymentPlan,
		arg.PioneerCreditLimitMicros,
		arg.PioneerRemainingMicros,
		arg.TodayMicros,
		arg.LastBillingSyncAt,
		arg.ID,
	)
	return err
}

const updatePoolKeyLimits = `-- name: UpdatePoolKeyLimits :exec
UPDATE pool_keys SET
    max_micros    = ?,
    shared_micros = ?
WHERE id = ? AND user_id = ?
`

type UpdatePoolKeyLimitsParams struct {
	MaxMicros    int64  `json:"max_micros"`
	SharedMicros int64  `json:"shared_micros"`
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
}

// Updates the two-budget limits. Server enforces 0 <= shared <= max.
func (q *Queries) UpdatePoolKeyLimits(ctx context.Context, arg UpdatePoolKeyLimitsParams) error {
	_, err := q.db.ExecContext(ctx, updatePoolKeyLimits,
		arg.MaxMicros,
		arg.SharedMicros,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updatePoolKeyTotalMicros = `-- name: UpdatePoolKeyTotalMicros :exec
UPDATE pool_keys SET total_micros = ? WHERE id = ?
`

type UpdatePoolKeyTotalMicrosParams struct {
	TotalMicros int64  `json:"total_micros"`
	ID          string `json:"id"`
}

func (q *Queries) UpdatePoolKeyTotalMicros(ctx context.Context, arg UpdatePoolKeyTotalMicrosParams) error {
	_, err := q.db.ExecContext(ctx, updatePoolKeyTotalMicros, arg.TotalMicros, arg.ID)
	return err
}
