// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pool_keys.sql

package store

import (
	"context"
	"database/sql"
)

const createPoolKey = `-- name: CreatePoolKey :one

INSERT INTO pool_keys (
    id, user_id, label, key_ciphertext, key_fingerprint,
    active, daily_limit_micros, today_date, today_micros,
    total_micros, request_count, created_at
) VALUES (?, ?, ?, ?, ?, 1, ?, 0, 0, 0, 0, ?)
RETURNING id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at
`

type CreatePoolKeyParams struct {
	ID               string `json:"id"`
	UserID           string `json:"user_id"`
	Label            string `json:"label"`
	KeyCiphertext    string `json:"key_ciphertext"`
	KeyFingerprint   string `json:"key_fingerprint"`
	DailyLimitMicros int64  `json:"daily_limit_micros"`
	CreatedAt        int64  `json:"created_at"`
}

// Pool key queries.
//
// Pool keys are pioneer.ai API keys contributed by users to the shared pool.
// The picker selects the active key with the least spend today that is still
// under its daily cap. Spend counters are maintained here; exact accounting
// lives in the spends table.
func (q *Queries) CreatePoolKey(ctx context.Context, arg CreatePoolKeyParams) (PoolKey, error) {
	row := q.db.QueryRowContext(ctx, createPoolKey,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.KeyCiphertext,
		arg.KeyFingerprint,
		arg.DailyLimitMicros,
		arg.CreatedAt,
	)
	var i PoolKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
	)
	return i, err
}

const deletePoolKey = `-- name: DeletePoolKey :exec
DELETE FROM pool_keys WHERE id = ? AND user_id = ?
`

type DeletePoolKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePoolKey(ctx context.Context, arg DeletePoolKeyParams) error {
	_, err := q.db.ExecContext(ctx, deletePoolKey, arg.ID, arg.UserID)
	return err
}

const getPoolKey = `-- name: GetPoolKey :one
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at FROM pool_keys WHERE id = ?
`

func (q *Queries) GetPoolKey(ctx context.Context, id string) (PoolKey, error) {
	row := q.db.QueryRowContext(ctx, getPoolKey, id)
	var i PoolKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
	)
	return i, err
}

const listPoolAllocations = `-- name: ListPoolAllocations :many
SELECT
    u.id            AS user_id,
    u.display_name,
    u.email,
    COUNT(pk.id)                                              AS key_count,
    COALESCE(SUM(CASE WHEN pk.active = 1 THEN pk.daily_limit_micros ELSE 0 END), 0) AS daily_limit_micros,
    COALESCE(SUM(CASE WHEN pk.active = 1 THEN pk.today_micros ELSE 0 END), 0)       AS today_micros,
    COALESCE(SUM(pk.total_micros), 0)                         AS total_micros,
    COALESCE(SUM(pk.request_count), 0)                        AS request_count
FROM pool_keys pk
JOIN users u ON u.id = pk.user_id
GROUP BY u.id, u.display_name, u.email
ORDER BY daily_limit_micros DESC
`

type ListPoolAllocationsRow struct {
	UserID           string      `json:"user_id"`
	DisplayName      string      `json:"display_name"`
	Email            string      `json:"email"`
	KeyCount         int64       `json:"key_count"`
	DailyLimitMicros interface{} `json:"daily_limit_micros"`
	TodayMicros      interface{} `json:"today_micros"`
	TotalMicros      interface{} `json:"total_micros"`
	RequestCount     interface{} `json:"request_count"`
}

// Per-user pool key stats: daily commitment, today's spend, all-time spend.
// Only users who have contributed at least one pool key appear.
func (q *Queries) ListPoolAllocations(ctx context.Context) ([]ListPoolAllocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoolAllocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoolAllocationsRow{}
	for rows.Next() {
		var i ListPoolAllocationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Email,
			&i.KeyCount,
			&i.DailyLimitMicros,
			&i.TodayMicros,
			&i.TotalMicros,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolKeys = `-- name: ListPoolKeys :many
SELECT pk.id, pk.user_id, pk.label, pk.key_ciphertext, pk.key_fingerprint, pk.active, pk.daily_limit_micros, pk.today_date, pk.today_micros, pk.total_micros, pk.request_count, pk.created_at, pk.last_used_at, pk.max_micros, pk.shared_micros, pk.pioneer_team_id, pk.pioneer_payment_plan, pk.pioneer_credit_limit_micros, pk.pioneer_remaining_micros, pk.pioneer_health, pk.pioneer_unhealthy_since, pk.pending_validation, pk.last_billing_sync_at, pk.revoked_at, u.display_name AS owner_name, u.email AS owner_email
FROM pool_keys pk
JOIN users u ON u.id = pk.user_id
ORDER BY pk.active DESC, pk.today_micros ASC
`

type ListPoolKeysRow struct {
	ID                       string         `json:"id"`
	UserID                   string         `json:"user_id"`
	Label                    string         `json:"label"`
	KeyCiphertext            string         `json:"key_ciphertext"`
	KeyFingerprint           string         `json:"key_fingerprint"`
	Active                   int64          `json:"active"`
	DailyLimitMicros         int64          `json:"daily_limit_micros"`
	TodayDate                int64          `json:"today_date"`
	TodayMicros              int64          `json:"today_micros"`
	TotalMicros              int64          `json:"total_micros"`
	RequestCount             int64          `json:"request_count"`
	CreatedAt                int64          `json:"created_at"`
	LastUsedAt               sql.NullInt64  `json:"last_used_at"`
	MaxMicros                int64          `json:"max_micros"`
	SharedMicros             int64          `json:"shared_micros"`
	PioneerTeamID            sql.NullString `json:"pioneer_team_id"`
	PioneerPaymentPlan       sql.NullString `json:"pioneer_payment_plan"`
	PioneerCreditLimitMicros sql.NullInt64  `json:"pioneer_credit_limit_micros"`
	PioneerRemainingMicros   sql.NullInt64  `json:"pioneer_remaining_micros"`
	PioneerHealth            int64          `json:"pioneer_health"`
	PioneerUnhealthySince    sql.NullInt64  `json:"pioneer_unhealthy_since"`
	PendingValidation        int64          `json:"pending_validation"`
	LastBillingSyncAt        sql.NullInt64  `json:"last_billing_sync_at"`
	RevokedAt                sql.NullInt64  `json:"revoked_at"`
	OwnerName                string         `json:"owner_name"`
	OwnerEmail               string         `json:"owner_email"`
}

// All keys (for the pool management page). Includes inactive and other users' keys.
func (q *Queries) ListPoolKeys(ctx context.Context) ([]ListPoolKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoolKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoolKeysRow{}
	for rows.Next() {
		var i ListPoolKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyCiphertext,
			&i.KeyFingerprint,
			&i.Active,
			&i.DailyLimitMicros,
			&i.TodayDate,
			&i.TodayMicros,
			&i.TotalMicros,
			&i.RequestCount,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.MaxMicros,
			&i.SharedMicros,
			&i.PioneerTeamID,
			&i.PioneerPaymentPlan,
			&i.PioneerCreditLimitMicros,
			&i.PioneerRemainingMicros,
			&i.PioneerHealth,
			&i.PioneerUnhealthySince,
			&i.PendingValidation,
			&i.LastBillingSyncAt,
			&i.RevokedAt,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolKeysForUser = `-- name: ListPoolKeysForUser :many
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at FROM pool_keys WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPoolKeysForUser(ctx context.Context, userID string) ([]PoolKey, error) {
	rows, err := q.db.QueryContext(ctx, listPoolKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolKey{}
	for rows.Next() {
		var i PoolKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyCiphertext,
			&i.KeyFingerprint,
			&i.Active,
			&i.DailyLimitMicros,
			&i.TodayDate,
			&i.TodayMicros,
			&i.TotalMicros,
			&i.RequestCount,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.MaxMicros,
			&i.SharedMicros,
			&i.PioneerTeamID,
			&i.PioneerPaymentPlan,
			&i.PioneerCreditLimitMicros,
			&i.PioneerRemainingMicros,
			&i.PioneerHealth,
			&i.PioneerUnhealthySince,
			&i.PendingValidation,
			&i.LastBillingSyncAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickPoolKey = `-- name: PickPoolKey :one
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at FROM pool_keys
WHERE active = 1
  AND (today_date < ?1 OR today_micros < daily_limit_micros)
ORDER BY
    CASE WHEN today_date < ?1 THEN 0 ELSE today_micros END ASC,
    RANDOM()  -- tiebreak
LIMIT 1
`

// Select the best key to use for a request: active, under daily cap,
// least spend today. Resets stale today_* counters are handled in Go
// (compare today_date to current UTC day and update if stale).
// ?1 = current UTC day (unix / 86400)
func (q *Queries) PickPoolKey(ctx context.Context, todayDate int64) (PoolKey, error) {
	row := q.db.QueryRowContext(ctx, pickPoolKey, todayDate)
	var i PoolKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
	)
	return i, err
}

const recordPoolKeySpend = `-- name: RecordPoolKeySpend :exec
UPDATE pool_keys
SET
    today_date   = CASE WHEN today_date < ?1 THEN ?1 ELSE today_date END,
    today_micros = CASE WHEN today_date < ?1 THEN ?2 ELSE today_micros + ?2 END,
    total_micros = total_micros + ?2,
    request_count = request_count + 1,
    last_used_at = ?3
WHERE id = ?4
`

type RecordPoolKeySpendParams struct {
	TodayDate   int64         `json:"today_date"`
	TodayMicros int64         `json:"today_micros"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ID          string        `json:"id"`
}

// Called after a request settles. Resets daily counter if the day rolled over.
// today_day is the current UTC day (unix / 86400).
func (q *Queries) RecordPoolKeySpend(ctx context.Context, arg RecordPoolKeySpendParams) error {
	_, err := q.db.ExecContext(ctx, recordPoolKeySpend,
		arg.TodayDate,
		arg.TodayMicros,
		arg.LastUsedAt,
		arg.ID,
	)
	return err
}

const setPoolKeyActive = `-- name: SetPoolKeyActive :exec
UPDATE pool_keys SET active = ? WHERE id = ? AND user_id = ?
`

type SetPoolKeyActiveParams struct {
	Active int64  `json:"active"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SetPoolKeyActive(ctx context.Context, arg SetPoolKeyActiveParams) error {
	_, err := q.db.ExecContext(ctx, setPoolKeyActive, arg.Active, arg.ID, arg.UserID)
	return err
}

const syncTodaySpend = `-- name: SyncTodaySpend :exec
UPDATE pool_keys
SET
    today_date   = ?1,
    today_micros = ?2,
    active = CASE
        WHEN ?2 >= daily_limit_micros THEN 0
        ELSE active
    END
WHERE id = ?3
`

type SyncTodaySpendParams struct {
	TodayDate   int64  `json:"today_date"`
	TodayMicros int64  `json:"today_micros"`
	ID          string `json:"id"`
}

// Called after fetching real spend from pioneer's billing API.
// Overwrites today_micros with the authoritative value.
// If the key is over its daily limit, also marks it inactive.
func (q *Queries) SyncTodaySpend(ctx context.Context, arg SyncTodaySpendParams) error {
	_, err := q.db.ExecContext(ctx, syncTodaySpend, arg.TodayDate, arg.TodayMicros, arg.ID)
	return err
}

const updatePoolKeyLabel = `-- name: UpdatePoolKeyLabel :exec
UPDATE pool_keys SET label = ? WHERE id = ? AND user_id = ?
`

type UpdatePoolKeyLabelParams struct {
	Label  string `json:"label"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdatePoolKeyLabel(ctx context.Context, arg UpdatePoolKeyLabelParams) error {
	_, err := q.db.ExecContext(ctx, updatePoolKeyLabel, arg.Label, arg.ID, arg.UserID)
	return err
}

const updatePoolKeyLimit = `-- name: UpdatePoolKeyLimit :exec
UPDATE pool_keys SET daily_limit_micros = ? WHERE id = ? AND user_id = ?
`

type UpdatePoolKeyLimitParams struct {
	DailyLimitMicros int64  `json:"daily_limit_micros"`
	ID               string `json:"id"`
	UserID           string `json:"user_id"`
}

func (q *Queries) UpdatePoolKeyLimit(ctx context.Context, arg UpdatePoolKeyLimitParams) error {
	_, err := q.db.ExecContext(ctx, updatePoolKeyLimit, arg.DailyLimitMicros, arg.ID, arg.UserID)
	return err
}
