// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pool.sql

package store

import (
	"context"
)

const poolActiveKeyCount = `-- name: PoolActiveKeyCount :one
SELECT COUNT(*) FROM api_keys WHERE revoked_at IS NULL
`

func (q *Queries) PoolActiveKeyCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, poolActiveKeyCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const poolContributorCount = `-- name: PoolContributorCount :one
SELECT COUNT(DISTINCT user_id) FROM contributions
`

func (q *Queries) PoolContributorCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, poolContributorCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const poolSpentSince = `-- name: PoolSpentSince :one
SELECT COALESCE(SUM(amount_micros), 0)
FROM spends
WHERE created_at >= ?
`

func (q *Queries) PoolSpentSince(ctx context.Context, createdAt int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, poolSpentSince, createdAt)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const poolTokensGuzzled = `-- name: PoolTokensGuzzled :one
SELECT
    COALESCE(SUM(input_tokens), 0)  AS input_tokens,
    COALESCE(SUM(output_tokens), 0) AS output_tokens
FROM spends
`

type PoolTokensGuzzledRow struct {
	InputTokens  interface{} `json:"input_tokens"`
	OutputTokens interface{} `json:"output_tokens"`
}

func (q *Queries) PoolTokensGuzzled(ctx context.Context) (PoolTokensGuzzledRow, error) {
	row := q.db.QueryRowContext(ctx, poolTokensGuzzled)
	var i PoolTokensGuzzledRow
	err := row.Scan(&i.InputTokens, &i.OutputTokens)
	return i, err
}

const poolTotalBalance = `-- name: PoolTotalBalance :one

SELECT
    COALESCE((SELECT SUM(amount_micros) FROM contributions), 0) -
    COALESCE((SELECT SUM(amount_micros) FROM spends), 0)
    AS balance_micros
`

// Pool-wide aggregates. Used by the public splash page; no auth required.
func (q *Queries) PoolTotalBalance(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, poolTotalBalance)
	var balance_micros int64
	err := row.Scan(&balance_micros)
	return balance_micros, err
}

const poolUserCount = `-- name: PoolUserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) PoolUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, poolUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
