// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pool_keys_multi_provider.sql

package store

import (
	"context"
)

const hasHealthyKeyForProvider = `-- name: HasHealthyKeyForProvider :one
SELECT 1 FROM pool_keys
WHERE active = 1
  AND revoked_at IS NULL
  AND pending_validation = 0
  AND provider_id = ?
  AND pioneer_health = 1
  AND (pioneer_remaining_micros IS NULL OR pioneer_remaining_micros > 10000000)
  AND today_micros < max_micros
LIMIT 1
`

// Check if there's at least one healthy key for a provider.
func (q *Queries) HasHealthyKeyForProvider(ctx context.Context, providerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasHealthyKeyForProvider, providerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listKeysByProvider = `-- name: ListKeysByProvider :many
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at, provider_id FROM pool_keys WHERE provider_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListKeysByProvider(ctx context.Context, providerID string) ([]PoolKey, error) {
	rows, err := q.db.QueryContext(ctx, listKeysByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolKey{}
	for rows.Next() {
		var i PoolKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.KeyCiphertext,
			&i.KeyFingerprint,
			&i.Active,
			&i.DailyLimitMicros,
			&i.TodayDate,
			&i.TodayMicros,
			&i.TotalMicros,
			&i.RequestCount,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.MaxMicros,
			&i.SharedMicros,
			&i.PioneerTeamID,
			&i.PioneerPaymentPlan,
			&i.PioneerCreditLimitMicros,
			&i.PioneerRemainingMicros,
			&i.PioneerHealth,
			&i.PioneerUnhealthySince,
			&i.PendingValidation,
			&i.LastBillingSyncAt,
			&i.RevokedAt,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickOwnKeyForProvider = `-- name: PickOwnKeyForProvider :one
SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at, provider_id FROM pool_keys
WHERE user_id = ?
  AND active = 1
  AND revoked_at IS NULL
  AND pending_validation = 0
  AND provider_id = ?
  AND pioneer_health = 1
  AND (pioneer_remaining_micros IS NULL OR pioneer_remaining_micros > 10000000)
  AND today_micros < max_micros
  AND max_micros > shared_micros
ORDER BY (max_micros - max(today_micros, shared_micros)) DESC, RANDOM()
LIMIT 1
`

type PickOwnKeyForProviderParams struct {
	UserID     string `json:"user_id"`
	ProviderID string `json:"provider_id"`
}

// User's own key with private budget for a specific provider.
func (q *Queries) PickOwnKeyForProvider(ctx context.Context, arg PickOwnKeyForProviderParams) (PoolKey, error) {
	row := q.db.QueryRowContext(ctx, pickOwnKeyForProvider, arg.UserID, arg.ProviderID)
	var i PoolKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
		&i.ProviderID,
	)
	return i, err
}

const pickPoolKeyForProvider = `-- name: PickPoolKeyForProvider :one

SELECT id, user_id, label, key_ciphertext, key_fingerprint, active, daily_limit_micros, today_date, today_micros, total_micros, request_count, created_at, last_used_at, max_micros, shared_micros, pioneer_team_id, pioneer_payment_plan, pioneer_credit_limit_micros, pioneer_remaining_micros, pioneer_health, pioneer_unhealthy_since, pending_validation, last_billing_sync_at, revoked_at, provider_id FROM pool_keys
WHERE active = 1
  AND revoked_at IS NULL
  AND pending_validation = 0
  AND provider_id = ?
  AND pioneer_health = 1
  AND (pioneer_remaining_micros IS NULL OR pioneer_remaining_micros > 10000000)
  AND today_micros < max_micros
ORDER BY today_micros ASC, RANDOM()
LIMIT 1
`

// Multi-provider pool key queries.
// These extend the v2 queries with provider_id filtering.
// Best active healthy key for a specific provider.
func (q *Queries) PickPoolKeyForProvider(ctx context.Context, providerID string) (PoolKey, error) {
	row := q.db.QueryRowContext(ctx, pickPoolKeyForProvider, providerID)
	var i PoolKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.KeyCiphertext,
		&i.KeyFingerprint,
		&i.Active,
		&i.DailyLimitMicros,
		&i.TodayDate,
		&i.TodayMicros,
		&i.TotalMicros,
		&i.RequestCount,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.MaxMicros,
		&i.SharedMicros,
		&i.PioneerTeamID,
		&i.PioneerPaymentPlan,
		&i.PioneerCreditLimitMicros,
		&i.PioneerRemainingMicros,
		&i.PioneerHealth,
		&i.PioneerUnhealthySince,
		&i.PendingValidation,
		&i.LastBillingSyncAt,
		&i.RevokedAt,
		&i.ProviderID,
	)
	return i, err
}
