// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: potluck_requests.sql

package store

import (
	"context"
	"database/sql"
)

const cancelPotluckRequest = `-- name: CancelPotluckRequest :exec
UPDATE potluck_requests SET
    finished_at = ?,
    status      = 'canceled'
WHERE id = ? AND status = 'pending'
`

type CancelPotluckRequestParams struct {
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) CancelPotluckRequest(ctx context.Context, arg CancelPotluckRequestParams) error {
	_, err := q.db.ExecContext(ctx, cancelPotluckRequest, arg.FinishedAt, arg.ID)
	return err
}

const createPotluckRequest = `-- name: CreatePotluckRequest :one

INSERT INTO potluck_requests (
    id, user_id, api_key_id, pool_key_id, surface, model, started_at, status
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
RETURNING id, user_id, api_key_id, pool_key_id, surface, model, started_at, finished_at, prompt_tokens, completion_tokens, total_tokens, status, error_code, provider_id
`

type CreatePotluckRequestParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	ApiKeyID  sql.NullString `json:"api_key_id"`
	PoolKeyID sql.NullString `json:"pool_key_id"`
	Surface   string         `json:"surface"`
	Model     string         `json:"model"`
	StartedAt int64          `json:"started_at"`
}

// potluck_requests: per-request log for attribution and billing join.
func (q *Queries) CreatePotluckRequest(ctx context.Context, arg CreatePotluckRequestParams) (PotluckRequest, error) {
	row := q.db.QueryRowContext(ctx, createPotluckRequest,
		arg.ID,
		arg.UserID,
		arg.ApiKeyID,
		arg.PoolKeyID,
		arg.Surface,
		arg.Model,
		arg.StartedAt,
	)
	var i PotluckRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.PoolKeyID,
		&i.Surface,
		&i.Model,
		&i.StartedAt,
		&i.FinishedAt,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.Status,
		&i.ErrorCode,
		&i.ProviderID,
	)
	return i, err
}

const finishPotluckRequest = `-- name: FinishPotluckRequest :exec
UPDATE potluck_requests SET
    finished_at       = ?,
    prompt_tokens     = ?,
    completion_tokens = ?,
    total_tokens      = ?,
    status            = ?
WHERE id = ?
`

type FinishPotluckRequestParams struct {
	FinishedAt       sql.NullInt64 `json:"finished_at"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	TotalTokens      sql.NullInt64 `json:"total_tokens"`
	Status           string        `json:"status"`
	ID               string        `json:"id"`
}

func (q *Queries) FinishPotluckRequest(ctx context.Context, arg FinishPotluckRequestParams) error {
	_, err := q.db.ExecContext(ctx, finishPotluckRequest,
		arg.FinishedAt,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.Status,
		arg.ID,
	)
	return err
}

const listUnmatchedRequestsForKey = `-- name: ListUnmatchedRequestsForKey :many
SELECT pr.id, pr.user_id, pr.api_key_id, pr.pool_key_id, pr.surface, pr.model, pr.started_at, pr.finished_at, pr.prompt_tokens, pr.completion_tokens, pr.total_tokens, pr.status, pr.error_code, pr.provider_id FROM potluck_requests pr
WHERE pr.pool_key_id = ?
  AND pr.finished_at >= ?
  AND pr.finished_at <= ?
  AND pr.status = 'done'
  AND pr.id NOT IN (
      SELECT pkbr.matched_request_id FROM pool_key_billing_rows pkbr
      WHERE pkbr.matched_request_id IS NOT NULL
  )
ORDER BY pr.finished_at ASC
`

type ListUnmatchedRequestsForKeyParams struct {
	PoolKeyID    sql.NullString `json:"pool_key_id"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	FinishedAt_2 sql.NullInt64  `json:"finished_at_2"`
}

// Requests that finished in a given time window with no billing row matched yet.
// Used by the reconciler attribution pass.
func (q *Queries) ListUnmatchedRequestsForKey(ctx context.Context, arg ListUnmatchedRequestsForKeyParams) ([]PotluckRequest, error) {
	rows, err := q.db.QueryContext(ctx, listUnmatchedRequestsForKey, arg.PoolKeyID, arg.FinishedAt, arg.FinishedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PotluckRequest{}
	for rows.Next() {
		var i PotluckRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.PoolKeyID,
			&i.Surface,
			&i.Model,
			&i.StartedAt,
			&i.FinishedAt,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.Status,
			&i.ErrorCode,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
