// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package store

import (
	"context"
)

const getModelPrice = `-- name: GetModelPrice :one
SELECT model, input_micros_per_1k, output_micros_per_1k, updated_at FROM model_prices WHERE model = ?
`

func (q *Queries) GetModelPrice(ctx context.Context, model string) (ModelPrice, error) {
	row := q.db.QueryRowContext(ctx, getModelPrice, model)
	var i ModelPrice
	err := row.Scan(
		&i.Model,
		&i.InputMicrosPer1k,
		&i.OutputMicrosPer1k,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelPrices = `-- name: ListModelPrices :many
SELECT model, input_micros_per_1k, output_micros_per_1k, updated_at FROM model_prices ORDER BY model ASC
`

func (q *Queries) ListModelPrices(ctx context.Context) ([]ModelPrice, error) {
	rows, err := q.db.QueryContext(ctx, listModelPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPrice{}
	for rows.Next() {
		var i ModelPrice
		if err := rows.Scan(
			&i.Model,
			&i.InputMicrosPer1k,
			&i.OutputMicrosPer1k,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelPrice = `-- name: UpsertModelPrice :exec
INSERT INTO model_prices (model, input_micros_per_1k, output_micros_per_1k, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(model) DO UPDATE SET
    input_micros_per_1k = excluded.input_micros_per_1k,
    output_micros_per_1k = excluded.output_micros_per_1k,
    updated_at = excluded.updated_at
`

type UpsertModelPriceParams struct {
	Model             string `json:"model"`
	InputMicrosPer1k  int64  `json:"input_micros_per_1k"`
	OutputMicrosPer1k int64  `json:"output_micros_per_1k"`
	UpdatedAt         int64  `json:"updated_at"`
}

func (q *Queries) UpsertModelPrice(ctx context.Context, arg UpsertModelPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelPrice,
		arg.Model,
		arg.InputMicrosPer1k,
		arg.OutputMicrosPer1k,
		arg.UpdatedAt,
	)
	return err
}
