// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package store

import (
	"context"
	"database/sql"
)

const getModelPrice = `-- name: GetModelPrice :one
SELECT model, input_micros_per_1k, output_micros_per_1k, updated_at FROM model_prices WHERE model = ?
`

func (q *Queries) GetModelPrice(ctx context.Context, model string) (ModelPrice, error) {
	row := q.db.QueryRowContext(ctx, getModelPrice, model)
	var i ModelPrice
	err := row.Scan(
		&i.Model,
		&i.InputMicrosPer1k,
		&i.OutputMicrosPer1k,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelPrices = `-- name: ListModelPrices :many
SELECT model, input_micros_per_1k, output_micros_per_1k, updated_at FROM model_prices ORDER BY model ASC
`

func (q *Queries) ListModelPrices(ctx context.Context) ([]ModelPrice, error) {
	rows, err := q.db.QueryContext(ctx, listModelPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPrice{}
	for rows.Next() {
		var i ModelPrice
		if err := rows.Scan(
			&i.Model,
			&i.InputMicrosPer1k,
			&i.OutputMicrosPer1k,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelStats = `-- name: ListModelStats :many
SELECT
    pkbr.model,
    COUNT(*)                                          AS request_count,
    SUM(COALESCE(pr.prompt_tokens, 0))                AS total_input_tokens,
    SUM(COALESCE(pr.completion_tokens, 0))            AS total_output_tokens,
    AVG(
        CASE
            WHEN pr.finished_at IS NOT NULL
             AND pr.finished_at > pr.started_at
             AND pr.started_at >= ?
            THEN CAST(COALESCE(pr.completion_tokens, 0) AS REAL)
                 / (pr.finished_at - pr.started_at)
            ELSE NULL
        END
    )                                                 AS avg_tps
FROM pool_key_billing_rows pkbr
LEFT JOIN potluck_requests pr ON pr.id = pkbr.matched_request_id
WHERE pkbr.is_duplicate = 0
GROUP BY pkbr.model
ORDER BY request_count DESC
`

type ListModelStatsRow struct {
	Model             string          `json:"model"`
	RequestCount      int64           `json:"request_count"`
	TotalInputTokens  sql.NullFloat64 `json:"total_input_tokens"`
	TotalOutputTokens sql.NullFloat64 `json:"total_output_tokens"`
	AvgTps            sql.NullFloat64 `json:"avg_tps"`
}

// Per-model aggregate from billing rows + potluck_requests.
// since scopes the TPS window (48h); cost/token counts are all-time.
func (q *Queries) ListModelStats(ctx context.Context, startedAt int64) ([]ListModelStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelStats, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelStatsRow{}
	for rows.Next() {
		var i ListModelStatsRow
		if err := rows.Scan(
			&i.Model,
			&i.RequestCount,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.AvgTps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelStatsFromRequests = `-- name: ListModelStatsFromRequests :many
SELECT
    model,
    COUNT(*)                                          AS request_count,
    SUM(COALESCE(prompt_tokens, 0))                   AS total_input_tokens,
    SUM(COALESCE(completion_tokens, 0))               AS total_output_tokens,
    AVG(
        CASE
            WHEN finished_at IS NOT NULL
             AND finished_at > started_at
             AND started_at >= ?
            THEN CAST(COALESCE(completion_tokens, 0) AS REAL)
                 / (finished_at - started_at)
            ELSE NULL
        END
    )                                                 AS avg_tps
FROM potluck_requests
WHERE status = 'done'
GROUP BY model
ORDER BY request_count DESC
`

type ListModelStatsFromRequestsRow struct {
	Model             string          `json:"model"`
	RequestCount      int64           `json:"request_count"`
	TotalInputTokens  sql.NullFloat64 `json:"total_input_tokens"`
	TotalOutputTokens sql.NullFloat64 `json:"total_output_tokens"`
	AvgTps            sql.NullFloat64 `json:"avg_tps"`
}

// Per-model aggregate directly from potluck_requests.
// Covers all providers (including those without billing rows).
// since scopes the TPS window (48h); token counts are all-time.
func (q *Queries) ListModelStatsFromRequests(ctx context.Context, startedAt int64) ([]ListModelStatsFromRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelStatsFromRequests, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelStatsFromRequestsRow{}
	for rows.Next() {
		var i ListModelStatsFromRequestsRow
		if err := rows.Scan(
			&i.Model,
			&i.RequestCount,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.AvgTps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelPrice = `-- name: UpsertModelPrice :exec
INSERT INTO model_prices (model, input_micros_per_1k, output_micros_per_1k, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(model) DO UPDATE SET
    input_micros_per_1k = excluded.input_micros_per_1k,
    output_micros_per_1k = excluded.output_micros_per_1k,
    updated_at = excluded.updated_at
`

type UpsertModelPriceParams struct {
	Model             string `json:"model"`
	InputMicrosPer1k  int64  `json:"input_micros_per_1k"`
	OutputMicrosPer1k int64  `json:"output_micros_per_1k"`
	UpdatedAt         int64  `json:"updated_at"`
}

func (q *Queries) UpsertModelPrice(ctx context.Context, arg UpsertModelPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelPrice,
		arg.Model,
		arg.InputMicrosPer1k,
		arg.OutputMicrosPer1k,
		arg.UpdatedAt,
	)
	return err
}
