// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package store

import (
	"context"
)

const createProvider = `-- name: CreateProvider :exec
INSERT INTO providers (id, type, name, base_url, config_json, active, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProviderParams struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Name       string `json:"name"`
	BaseUrl    string `json:"base_url"`
	ConfigJson string `json:"config_json"`
	Active     int64  `json:"active"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) error {
	_, err := q.db.ExecContext(ctx, createProvider,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.BaseUrl,
		arg.ConfigJson,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, type, name, base_url, config_json, active, created_at FROM providers WHERE id = ?
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.ConfigJson,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveProviders = `-- name: ListActiveProviders :many

SELECT id, type, name, base_url, config_json, active, created_at FROM providers WHERE active = 1 ORDER BY id
`

// Provider registry queries for multi-provider support.
func (q *Queries) ListActiveProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.BaseUrl,
			&i.ConfigJson,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE providers SET
    type        = ?,
    name        = ?,
    base_url    = ?,
    config_json = ?,
    active      = ?
WHERE id = ?
`

type UpdateProviderParams struct {
	Type       string `json:"type"`
	Name       string `json:"name"`
	BaseUrl    string `json:"base_url"`
	ConfigJson string `json:"config_json"`
	Active     int64  `json:"active"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateProvider,
		arg.Type,
		arg.Name,
		arg.BaseUrl,
		arg.ConfigJson,
		arg.Active,
		arg.ID,
	)
	return err
}
