// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Called by the reconciler when a pending_validation or unauthorized key
	// comes back healthy (pioneer_health=1).
	ActivatePoolKey(ctx context.Context, id string) error
	AddAPIKeySpend(ctx context.Context, arg AddAPIKeySpendParams) error
	AppendAssistantContent(ctx context.Context, arg AppendAssistantContentParams) error
	AppendStreamChunk(ctx context.Context, arg AppendStreamChunkParams) error
	ArchiveConversation(ctx context.Context, arg ArchiveConversationParams) error
	CancelPotluckRequest(ctx context.Context, arg CancelPotluckRequestParams) error
	CountActiveStreamsForUser(ctx context.Context, userID string) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	// Pool key queries.
	//
	// Pool keys are pioneer.ai API keys contributed by users to the shared pool.
	// The picker selects the active key with the least spend today that is still
	// under its daily cap. Spend counters are maintained here; exact accounting
	// lives in the spends table.
	CreatePoolKey(ctx context.Context, arg CreatePoolKeyParams) (PoolKey, error)
	// potluck_requests: per-request log for attribution and billing join.
	CreatePotluckRequest(ctx context.Context, arg CreatePotluckRequestParams) (PotluckRequest, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllSessionsForUser(ctx context.Context, userID string) error
	DeleteExpiredIdempotency(ctx context.Context, expiresAt int64) error
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) error
	DeletePoolKey(ctx context.Context, arg DeletePoolKeyParams) error
	DeleteProvider(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) error
	DeleteUserByID(ctx context.Context, id string) error
	DeleteUserMemoryKey(ctx context.Context, arg DeleteUserMemoryKeyParams) error
	FinishPotluckRequest(ctx context.Context, arg FinishPotluckRequestParams) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error)
	GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error)
	// Most recent recompute for today, for display in the dashboard.
	GetLatestRecompute(ctx context.Context, day int64) (GetLatestRecomputeRow, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	// Oldest refreshed_at across all models — tells us when the catalog is stale.
	GetModelCatalogRefreshedAt(ctx context.Context) (interface{}, error)
	GetModelPrice(ctx context.Context, model string) (ModelPrice, error)
	GetPoolKey(ctx context.Context, id string) (PoolKey, error)
	GetProvider(ctx context.Context, id string) (Provider, error)
	// Returns the most-recently-started stream for a conversation that is
	// currently running. Used by handleConversationEvents to bootstrap
	// observers who connect after the stream has already started.
	GetRunningStreamForConversation(ctx context.Context, conversationID string) (Stream, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetStream(ctx context.Context, id string) (Stream, error)
	GetStreamByIdempotencyKey(ctx context.Context, arg GetStreamByIdempotencyKeyParams) (Stream, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByHCAID(ctx context.Context, hcaID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserDailyAllowance(ctx context.Context, arg GetUserDailyAllowanceParams) (UserDailyAllowance, error)
	GetUserDailySpend(ctx context.Context, arg GetUserDailySpendParams) (UserDailySpend, error)
	// Live spend for a user since the start of the current UTC day, read
	// directly from billing rows. Used by PoolGate for accurate pre-flight
	// checks without waiting for the reconciler to flush user_daily_spend.
	// Splits into shared vs private: private = rows where the user owns the
	// key and the key has a non-zero private reservation (max > shared).
	GetUserLiveSpendToday(ctx context.Context, arg GetUserLiveSpendTodayParams) (GetUserLiveSpendTodayRow, error)
	GetUserMemory(ctx context.Context, userID string) ([]UserMemory, error)
	GetUserMemoryKey(ctx context.Context, arg GetUserMemoryKeyParams) (UserMemory, error)
	// Check if there's at least one healthy key for a provider.
	HasHealthyKeyForProvider(ctx context.Context, providerID string) (int64, error)
	// Most recent pioneer_created_at for a key.
	// COALESCE(SUM(pioneer_created_at*0) + MAX(...)) is a workaround for
	// sqlc's sqlite parser rejecting bare COALESCE(MAX(...), 0).
	LatestBillingRowTime(ctx context.Context, poolKeyID string) (interface{}, error)
	ListAPIKeysForUser(ctx context.Context, userID string) ([]ApiKey, error)
	// Provider registry queries for multi-provider support.
	ListActiveProviders(ctx context.Context) ([]Provider, error)
	ListAllProviders(ctx context.Context) ([]Provider, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	// Live spend for ALL users since dayStart, grouped by user.
	// Used by RunSmartAllocation so it doesn't depend on the stale
	// user_daily_spend cache.
	ListAllUsersLiveSpendToday(ctx context.Context, pioneerCreatedAt int64) ([]ListAllUsersLiveSpendTodayRow, error)
	// All billing rows for a key after a given timestamp.
	ListBillingRowsForKeyAfter(ctx context.Context, arg ListBillingRowsForKeyAfterParams) ([]PoolKeyBillingRow, error)
	// Billing rows attributed to a user in a time window.
	// Caller filters duplicates and sums in Go.
	ListBillingRowsForUserBetween(ctx context.Context, arg ListBillingRowsForUserBetweenParams) ([]PoolKeyBillingRow, error)
	ListContributionsForUser(ctx context.Context, arg ListContributionsForUserParams) ([]Contribution, error)
	ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]Conversation, error)
	ListEstimatedSpends(ctx context.Context, limit int64) ([]Spend, error)
	ListKeysByProvider(ctx context.Context, providerID string) ([]PoolKey, error)
	// Keys the reconciler should probe on each tick.
	// Excludes permanently revoked keys.
	ListKeysNeedingHealthCheck(ctx context.Context) ([]PoolKey, error)
	ListMessagesForConversation(ctx context.Context, conversationID string) ([]Message, error)
	ListModelCatalog(ctx context.Context) ([]ModelsCatalog, error)
	ListModelPrices(ctx context.Context) ([]ModelPrice, error)
	// Per-model aggregate from billing rows + potluck_requests.
	// since scopes the TPS window (48h); cost/token counts are all-time.
	ListModelStats(ctx context.Context, startedAt int64) ([]ListModelStatsRow, error)
	// All users with their pool key stats (if any).
	// Users without keys appear with zero contributions.
	// private_reservation_micros = sum(max_micros - shared_micros) for active keys.
	// today_micros capped at shared_micros: a key whose credit limit dropped (e.g.
	// $1000->$50) can't report more pool spend than its current contribution.
	ListPoolAllocations(ctx context.Context) ([]ListPoolAllocationsRow, error)
	// All keys (for the pool management page). Includes inactive and other users' keys.
	ListPoolKeys(ctx context.Context) ([]ListPoolKeysRow, error)
	ListPoolKeysForUser(ctx context.Context, userID string) ([]PoolKey, error)
	ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error)
	ListStreamChunksAfter(ctx context.Context, arg ListStreamChunksAfterParams) ([]ListStreamChunksAfterRow, error)
	// Keys that have been unauthorized (pioneer_health=2) since before cutoff.
	// Used by the reconciler to trigger permanent revocation after 14 days.
	ListUnhealthyKeysOlderThan(ctx context.Context, pioneerUnhealthySince sql.NullInt64) ([]PoolKey, error)
	// Requests that finished in a given time window with no billing row matched yet.
	// Used by the reconciler attribution pass.
	ListUnmatchedRequestsForKey(ctx context.Context, arg ListUnmatchedRequestsForKeyParams) ([]PotluckRequest, error)
	// Per-user contribution totals, spend totals, and derived balance.
	// Used by the allocation calculator on the dashboard.
	ListUserAllocations(ctx context.Context) ([]ListUserAllocationsRow, error)
	ListUserDailyAllowancesForDay(ctx context.Context, day int64) ([]UserDailyAllowance, error)
	ListUserDailySpendForDay(ctx context.Context, day int64) ([]UserDailySpend, error)
	MarkPoolKeyRevoked(ctx context.Context, arg MarkPoolKeyRevokedParams) error
	MaxStreamChunkSeq(ctx context.Context, streamID string) (interface{}, error)
	// User's own key with private budget for a specific provider.
	PickOwnKeyForProvider(ctx context.Context, arg PickOwnKeyForProviderParams) (PoolKey, error)
	// First leg of user-aware picking: try to find the user's own key that
	// still has private reservation room (max_micros > shared_micros).
	// If this returns no rows, fall back to PickPoolKeyV2.
	//
	// Orders by remaining private budget (most remaining first) so that when a
	// user has multiple keys with private reserves we pick the one with the most
	// headroom; this avoids over-draining a single key from shared pool traffic.
	// RANDOM() tie-break ensures cycling when keys have equal private remaining.
	PickOwnKeyWithPrivateBudget(ctx context.Context, userID string) (PoolKey, error)
	// Select the best key to use for a request: active, under daily cap,
	// least spend today. Resets stale today_* counters are handled in Go
	// (compare today_date to current UTC day and update if stale).
	// ?1 = current UTC day (unix / 86400)
	PickPoolKey(ctx context.Context, todayDate int64) (PoolKey, error)
	// Multi-provider pool key queries.
	// These extend the v2 queries with provider_id filtering.
	// Best active healthy key for a specific provider.
	PickPoolKeyForProvider(ctx context.Context, providerID string) (PoolKey, error)
	// Best active healthy key for a request:
	//   active=1, not revoked, not pending validation
	//   pioneer_health=1 (healthy)
	//   pioneer_remaining_micros > 10,000,000 ($10 buffer = 1000 credits)
	//   today_micros < max_micros
	// Lowest today_micros wins; random tiebreak.
	PickPoolKeyV2(ctx context.Context) (PoolKey, error)
	PoolActiveKeyCount(ctx context.Context) (int64, error)
	// Users who own at least one active pool key.
	PoolContributorCount(ctx context.Context) (int64, error)
	// Spend (cost_micros) from billing rows since the given unix timestamp.
	// Excludes duplicates.
	PoolSpentSince(ctx context.Context, pioneerCreatedAt int64) (interface{}, error)
	// token_usage is the total per row; split evenly across input/output so
	// the caller's inTok+outTok sum equals the real total.
	PoolTokensGuzzled(ctx context.Context) (PoolTokensGuzzledRow, error)
	// Pool-wide aggregates. Used by the public splash page; no auth required.
	// Total pioneer credit limit across all active pool keys.
	PoolTotalBalance(ctx context.Context) (interface{}, error)
	PoolUserCount(ctx context.Context) (int64, error)
	// Delete models for a provider prefix that weren't refreshed in the current cycle.
	// The first arg is the LIKE pattern (e.g. "nvidia/%").
	PruneStaleModels(ctx context.Context, arg PruneStaleModelsParams) (int64, error)
	PutIdempotency(ctx context.Context, arg PutIdempotencyParams) error
	// Called after a request settles. Resets daily counter if the day rolled over.
	// today_day is the current UTC day (unix / 86400).
	RecordPoolKeySpend(ctx context.Context, arg RecordPoolKeySpendParams) error
	RenameAPIKey(ctx context.Context, arg RenameAPIKeyParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SetPoolKeyActive(ctx context.Context, arg SetPoolKeyActiveParams) error
	SetStreamStatus(ctx context.Context, arg SetStreamStatusParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	// Daily spend for a user over the last N days, from billing rows.
	// Only potluck-routed rows (matched_request_id IS NOT NULL) are included.
	SpendByDay(ctx context.Context, arg SpendByDayParams) ([]SpendByDayRow, error)
	// Daily spend broken down by model for a user, for stacked chart.
	SpendByDayAndModel(ctx context.Context, arg SpendByDayAndModelParams) ([]SpendByDayAndModelRow, error)
	// Total non-duplicate cost for a key, all time. Used to keep
	// pool_keys.total_micros accurate after reconciliation.
	SumBillingRowsForKey(ctx context.Context, poolKeyID string) (interface{}, error)
	SumContributions(ctx context.Context, userID string) (interface{}, error)
	SumSpends(ctx context.Context, userID string) (interface{}, error)
	// Updates display name from cachet only if the user hasn't set a custom name.
	SyncDisplayName(ctx context.Context, arg SyncDisplayNameParams) error
	// Called by the reconciler to keep max_micros in sync with pioneer's reported
	// credit_limit. Clamps shared_micros to the new max so it never exceeds it.
	// Does NOT require user_id; reconciler owns this path.
	SyncPoolKeyMaxFromCreditLimit(ctx context.Context, arg SyncPoolKeyMaxFromCreditLimitParams) error
	// Called after fetching real spend from pioneer's billing API.
	// Overwrites today_micros with the authoritative value.
	// If the key is over its daily limit, also marks it inactive.
	SyncTodaySpend(ctx context.Context, arg SyncTodaySpendParams) error
	// Debounced caller: only call when last_used_at is older than 60s.
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchConversation(ctx context.Context, arg TouchConversationParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TouchUser(ctx context.Context, arg TouchUserParams) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error
	// Sets display name and marks it as custom so cachet sync backs off.
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) error
	// Pool key v2 queries: health tracking, billing sync, two-budget updates.
	//
	// pioneer_health integer enum:
	//   0 = unknown
	//   1 = healthy
	//   2 = unauthorized
	// Sets health and snapshots billing info from /plan-info.
	// Pass NULL for optional fields to leave them unchanged.
	UpdatePoolKeyHealth(ctx context.Context, arg UpdatePoolKeyHealthParams) error
	UpdatePoolKeyLabel(ctx context.Context, arg UpdatePoolKeyLabelParams) error
	UpdatePoolKeyLimit(ctx context.Context, arg UpdatePoolKeyLimitParams) error
	// Updates the two-budget limits. Server enforces 0 <= shared <= max.
	UpdatePoolKeyLimits(ctx context.Context, arg UpdatePoolKeyLimitsParams) error
	UpdatePoolKeyTotalMicros(ctx context.Context, arg UpdatePoolKeyTotalMicrosParams) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) error
	// pool_key_billing_rows: ingested pioneer billing log entries.
	//
	// attribution integer enum:
	//   0 = matched        (joined to a potluck_requests row)
	//   1 = judge_paired   (/llmaj/judge paired to preceding opus call)
	//   2 = owner_fallback (no match, charged to key owner)
	//   3 = duplicate      (double-logged by pioneer, not charged)
	UpsertBillingRow(ctx context.Context, arg UpsertBillingRowParams) error
	UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Message, error)
	// models_catalog: hourly-refreshed cache of /v1/models + /base-models.
	UpsertModelCatalog(ctx context.Context, arg UpsertModelCatalogParams) error
	UpsertModelPrice(ctx context.Context, arg UpsertModelPriceParams) error
	UpsertSpend(ctx context.Context, arg UpsertSpendParams) (Spend, error)
	// Find-or-create by HCA id. Email and slack_id are refreshed on every login.
	// display_name is never set from HCA - cachet is the sole source of truth
	// and syncCachetName updates it immediately after upsert.
	// status and is_admin are intentionally NOT updated on conflict so a banned
	// user can't reset their own status by logging in again.
	UpsertUserByHCAID(ctx context.Context, arg UpsertUserByHCAIDParams) (User, error)
	// Always overwrites with the computed breakdown.
	// shared_allowance_micros should equal floor_micros + bonus_micros.
	UpsertUserDailyAllowance(ctx context.Context, arg UpsertUserDailyAllowanceParams) error
	// user_daily_spend and user_daily_allowances.
	UpsertUserDailySpend(ctx context.Context, arg UpsertUserDailySpendParams) error
	UpsertUserMemory(ctx context.Context, arg UpsertUserMemoryParams) error
	// Per-user historical spend profile over a time window.
	// Returns one row per user, with total non-duplicate spend and the count
	// of distinct UTC days that had any spend. Used by smartAllocate for
	// demand prediction.
	//
	// ?1 = window start (unix seconds, inclusive)
	// ?2 = window end   (unix seconds, exclusive)
	UserHistoryProfile(ctx context.Context, arg UserHistoryProfileParams) ([]UserHistoryProfileRow, error)
}

var _ Querier = (*Queries)(nil)
