// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package store

import (
	"context"
	"database/sql"
)

const appendStreamChunk = `-- name: AppendStreamChunk :exec
INSERT INTO stream_chunks (stream_id, seq, event, data, created_at)
VALUES (?, ?, ?, ?, ?)
`

type AppendStreamChunkParams struct {
	StreamID  string `json:"stream_id"`
	Seq       int64  `json:"seq"`
	Event     string `json:"event"`
	Data      string `json:"data"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) AppendStreamChunk(ctx context.Context, arg AppendStreamChunkParams) error {
	_, err := q.db.ExecContext(ctx, appendStreamChunk,
		arg.StreamID,
		arg.Seq,
		arg.Event,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const countActiveStreamsForUser = `-- name: CountActiveStreamsForUser :one
SELECT COUNT(*) FROM streams
WHERE user_id = ? AND status IN ('pending', 'running')
`

func (q *Queries) CountActiveStreamsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveStreamsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStream = `-- name: CreateStream :one
INSERT INTO streams (
    id, conversation_id, user_id, assistant_message_id, idempotency_key,
    model, status, started_at
) VALUES (?, ?, ?, ?, ?, ?, 'pending', ?)
RETURNING id, conversation_id, user_id, assistant_message_id, idempotency_key, model, status, error_code, error_message, started_at, finished_at
`

type CreateStreamParams struct {
	ID                 string         `json:"id"`
	ConversationID     string         `json:"conversation_id"`
	UserID             string         `json:"user_id"`
	AssistantMessageID sql.NullString `json:"assistant_message_id"`
	IdempotencyKey     string         `json:"idempotency_key"`
	Model              string         `json:"model"`
	StartedAt          int64          `json:"started_at"`
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error) {
	row := q.db.QueryRowContext(ctx, createStream,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.AssistantMessageID,
		arg.IdempotencyKey,
		arg.Model,
		arg.StartedAt,
	)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.AssistantMessageID,
		&i.IdempotencyKey,
		&i.Model,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStream = `-- name: GetStream :one
SELECT id, conversation_id, user_id, assistant_message_id, idempotency_key, model, status, error_code, error_message, started_at, finished_at FROM streams WHERE id = ?
`

func (q *Queries) GetStream(ctx context.Context, id string) (Stream, error) {
	row := q.db.QueryRowContext(ctx, getStream, id)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.AssistantMessageID,
		&i.IdempotencyKey,
		&i.Model,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStreamByIdempotencyKey = `-- name: GetStreamByIdempotencyKey :one
SELECT id, conversation_id, user_id, assistant_message_id, idempotency_key, model, status, error_code, error_message, started_at, finished_at FROM streams WHERE user_id = ? AND idempotency_key = ?
`

type GetStreamByIdempotencyKeyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetStreamByIdempotencyKey(ctx context.Context, arg GetStreamByIdempotencyKeyParams) (Stream, error) {
	row := q.db.QueryRowContext(ctx, getStreamByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.AssistantMessageID,
		&i.IdempotencyKey,
		&i.Model,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listStreamChunksAfter = `-- name: ListStreamChunksAfter :many
SELECT seq, event, data, created_at
FROM stream_chunks
WHERE stream_id = ? AND seq > ?
ORDER BY seq ASC
`

type ListStreamChunksAfterParams struct {
	StreamID string `json:"stream_id"`
	Seq      int64  `json:"seq"`
}

type ListStreamChunksAfterRow struct {
	Seq       int64  `json:"seq"`
	Event     string `json:"event"`
	Data      string `json:"data"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListStreamChunksAfter(ctx context.Context, arg ListStreamChunksAfterParams) ([]ListStreamChunksAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listStreamChunksAfter, arg.StreamID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStreamChunksAfterRow{}
	for rows.Next() {
		var i ListStreamChunksAfterRow
		if err := rows.Scan(
			&i.Seq,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxStreamChunkSeq = `-- name: MaxStreamChunkSeq :one
SELECT COALESCE(MAX(seq), 0) FROM stream_chunks WHERE stream_id = ?
`

func (q *Queries) MaxStreamChunkSeq(ctx context.Context, streamID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxStreamChunkSeq, streamID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const setStreamStatus = `-- name: SetStreamStatus :exec
UPDATE streams SET status = ?, finished_at = ?, error_code = ?, error_message = ?
WHERE id = ?
`

type SetStreamStatusParams struct {
	Status       string         `json:"status"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) SetStreamStatus(ctx context.Context, arg SetStreamStatusParams) error {
	_, err := q.db.ExecContext(ctx, setStreamStatus,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

// GetRunningStreamForConversation returns the most-recently-started stream for
// a conversation that is currently running. Used by handleConversationEvents to
// bootstrap observers who connect after the stream has already started.
func (q *Queries) GetRunningStreamForConversation(ctx context.Context, conversationID string) (Stream, error) {
	const q2 = `SELECT id, conversation_id, user_id, assistant_message_id, idempotency_key, model, status, error_code, error_message, started_at, finished_at
FROM streams WHERE conversation_id = ? AND status = 'running' ORDER BY started_at DESC LIMIT 1`
	row := q.db.QueryRowContext(ctx, q2, conversationID)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.AssistantMessageID,
		&i.IdempotencyKey,
		&i.Model,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
