// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package store

import (
	"context"
	"database/sql"
)

const spendByDay = `-- name: SpendByDay :many
SELECT
    (pkbr.pioneer_created_at / 86400) * 86400  AS day,
    SUM(pkbr.cost_micros)                       AS amount_micros,
    SUM(COALESCE(pr.prompt_tokens, 0))          AS input_tokens,
    SUM(COALESCE(pr.completion_tokens, 0))      AS output_tokens
FROM pool_key_billing_rows pkbr
LEFT JOIN potluck_requests pr ON pr.id = pkbr.matched_request_id
WHERE pkbr.attributed_user_id = ?
  AND pkbr.pioneer_created_at >= ?
  AND pkbr.is_duplicate = 0
  AND pkbr.matched_request_id IS NOT NULL
GROUP BY day
ORDER BY day ASC
`

type SpendByDayParams struct {
	AttributedUserID sql.NullString `json:"attributed_user_id"`
	PioneerCreatedAt int64          `json:"pioneer_created_at"`
}

type SpendByDayRow struct {
	Day          int64           `json:"day"`
	AmountMicros sql.NullFloat64 `json:"amount_micros"`
	InputTokens  sql.NullFloat64 `json:"input_tokens"`
	OutputTokens sql.NullFloat64 `json:"output_tokens"`
}

// Daily spend for a user over the last N days, from billing rows.
// Only potluck-routed rows (matched_request_id IS NOT NULL) are included.
func (q *Queries) SpendByDay(ctx context.Context, arg SpendByDayParams) ([]SpendByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, spendByDay, arg.AttributedUserID, arg.PioneerCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByDayRow{}
	for rows.Next() {
		var i SpendByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.AmountMicros,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendByDayAndModel = `-- name: SpendByDayAndModel :many
;

SELECT
    (pkbr.pioneer_created_at / 86400) * 86400  AS day,
    pkbr.model,
    SUM(pkbr.cost_micros)                       AS amount_micros,
    SUM(COALESCE(pr.prompt_tokens, 0))          AS input_tokens,
    SUM(COALESCE(pr.completion_tokens, 0))      AS output_tokens
FROM pool_key_billing_rows pkbr
LEFT JOIN potluck_requests pr ON pr.id = pkbr.matched_request_id
WHERE pkbr.attributed_user_id = ?
  AND pkbr.pioneer_created_at >= ?
  AND pkbr.is_duplicate = 0
  AND pkbr.matched_request_id IS NOT NULL
GROUP BY day, pkbr.model
ORDER BY day ASC, amount_micros DESC
`

type SpendByDayAndModelParams struct {
	AttributedUserID sql.NullString `json:"attributed_user_id"`
	PioneerCreatedAt int64          `json:"pioneer_created_at"`
}

type SpendByDayAndModelRow struct {
	Day          int64           `json:"day"`
	Model        string          `json:"model"`
	AmountMicros sql.NullFloat64 `json:"amount_micros"`
	InputTokens  sql.NullFloat64 `json:"input_tokens"`
	OutputTokens sql.NullFloat64 `json:"output_tokens"`
}

// Daily spend broken down by model for a user, for stacked chart.
func (q *Queries) SpendByDayAndModel(ctx context.Context, arg SpendByDayAndModelParams) ([]SpendByDayAndModelRow, error) {
	rows, err := q.db.QueryContext(ctx, spendByDayAndModel, arg.AttributedUserID, arg.PioneerCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByDayAndModelRow{}
	for rows.Next() {
		var i SpendByDayAndModelRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.AmountMicros,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
