// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package store

import (
	"context"
	"database/sql"
)

const spendByDay = `-- name: SpendByDay :many
SELECT
    (created_at / 86400) * 86400          AS day,
    SUM(amount_micros)                     AS amount_micros,
    SUM(input_tokens)                      AS input_tokens,
    SUM(output_tokens)                     AS output_tokens
FROM spends
WHERE user_id = ?
  AND created_at >= ?
GROUP BY day
ORDER BY day ASC
`

type SpendByDayParams struct {
	UserID    string `json:"user_id"`
	CreatedAt int64  `json:"created_at"`
}

type SpendByDayRow struct {
	Day          int64           `json:"day"`
	AmountMicros sql.NullFloat64 `json:"amount_micros"`
	InputTokens  sql.NullFloat64 `json:"input_tokens"`
	OutputTokens sql.NullFloat64 `json:"output_tokens"`
}

// Daily spend for a user over the last N days.
// Returns one row per day (epoch of start of day in UTC) + amount in micros.
func (q *Queries) SpendByDay(ctx context.Context, arg SpendByDayParams) ([]SpendByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, spendByDay, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByDayRow{}
	for rows.Next() {
		var i SpendByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.AmountMicros,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendByDayAndModel = `-- name: SpendByDayAndModel :many
SELECT
    (created_at / 86400) * 86400          AS day,
    model,
    SUM(amount_micros)                     AS amount_micros,
    SUM(input_tokens)                      AS input_tokens,
    SUM(output_tokens)                     AS output_tokens
FROM spends
WHERE user_id = ?
  AND created_at >= ?
GROUP BY day, model
ORDER BY day ASC, amount_micros DESC
`

type SpendByDayAndModelParams struct {
	UserID    string `json:"user_id"`
	CreatedAt int64  `json:"created_at"`
}

type SpendByDayAndModelRow struct {
	Day          int64           `json:"day"`
	Model        string          `json:"model"`
	AmountMicros sql.NullFloat64 `json:"amount_micros"`
	InputTokens  sql.NullFloat64 `json:"input_tokens"`
	OutputTokens sql.NullFloat64 `json:"output_tokens"`
}

// Daily spend broken down by model for a user, for stacked chart.
func (q *Queries) SpendByDayAndModel(ctx context.Context, arg SpendByDayAndModelParams) ([]SpendByDayAndModelRow, error) {
	rows, err := q.db.QueryContext(ctx, spendByDayAndModel, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByDayAndModelRow{}
	for rows.Next() {
		var i SpendByDayAndModelRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.AmountMicros,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
