// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, email, display_name, created_at, last_seen_at, hca_id, slack_id, verification_status
`

type CreateUserParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.HcaID,
		&i.SlackID,
		&i.VerificationStatus,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, created_at, last_seen_at, hca_id, slack_id, verification_status FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.HcaID,
		&i.SlackID,
		&i.VerificationStatus,
	)
	return i, err
}

const getUserByHCAID = `-- name: GetUserByHCAID :one
SELECT id, email, display_name, created_at, last_seen_at, hca_id, slack_id, verification_status FROM users WHERE hca_id = ?
`

func (q *Queries) GetUserByHCAID(ctx context.Context, hcaID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHCAID, hcaID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.HcaID,
		&i.SlackID,
		&i.VerificationStatus,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, created_at, last_seen_at, hca_id, slack_id, verification_status FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.HcaID,
		&i.SlackID,
		&i.VerificationStatus,
	)
	return i, err
}

const touchUser = `-- name: TouchUser :exec
UPDATE users SET last_seen_at = ? WHERE id = ?
`

type TouchUserParams struct {
	LastSeenAt sql.NullInt64 `json:"last_seen_at"`
	ID         string        `json:"id"`
}

func (q *Queries) TouchUser(ctx context.Context, arg TouchUserParams) error {
	_, err := q.db.ExecContext(ctx, touchUser, arg.LastSeenAt, arg.ID)
	return err
}

const updateDisplayName = `-- name: UpdateDisplayName :exec
UPDATE users SET display_name = ? WHERE id = ?
`

type UpdateDisplayNameParams struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateDisplayName, arg.DisplayName, arg.ID)
	return err
}

const upsertUserByHCAID = `-- name: UpsertUserByHCAID :one
INSERT INTO users (
    id, email, display_name, hca_id, slack_id, verification_status, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(hca_id) DO UPDATE SET
    email = excluded.email,
    display_name = CASE WHEN display_name = '' OR display_name IS NULL
                        THEN excluded.display_name
                        ELSE display_name
                   END,
    slack_id = excluded.slack_id,
    verification_status = excluded.verification_status
RETURNING id, email, display_name, created_at, last_seen_at, hca_id, slack_id, verification_status
`

type UpsertUserByHCAIDParams struct {
	ID                 string         `json:"id"`
	Email              string         `json:"email"`
	DisplayName        string         `json:"display_name"`
	HcaID              sql.NullString `json:"hca_id"`
	SlackID            sql.NullString `json:"slack_id"`
	VerificationStatus sql.NullString `json:"verification_status"`
	CreatedAt          int64          `json:"created_at"`
}

// Find-or-create by HCA id, refreshing the cached identity fields on each
// successful sign-in. Email is updated because HCA emails can change.
// display_name is only set from HCA on first login; manual renames are
// preserved by keeping the existing value when it's already non-empty.
func (q *Queries) UpsertUserByHCAID(ctx context.Context, arg UpsertUserByHCAIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByHCAID,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.HcaID,
		arg.SlackID,
		arg.VerificationStatus,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.HcaID,
		&i.SlackID,
		&i.VerificationStatus,
	)
	return i, err
}
